// stats-data.js
// International IT & Digital Economy Statistics
// Sources: WIPO, IMD, UN, Portulans Institute, Startup Genome, ITU
// Data fetched and verified March 2025 from official sources and primary publications.

const STATS_INDEXES = {

    // ─────────────────────────────────────────────
    // 1. GLOBAL INNOVATION INDEX (GII) 2024 — WIPO
    // Source: worldpopulationreview.com/country-rankings/global-innovation-index-by-country
    //         (citing official WIPO GII 2024 data, 133 economies)
    // ─────────────────────────────────────────────
    gii: {
        id: 'gii',
        name: 'Global Innovation Index',
        shortName: 'GII',
        year: 2024,
        publisher: 'WIPO',
        publisherFull: 'World Intellectual Property Organization',
        sourceUrl: 'https://www.wipo.int/web-publications/global-innovation-index-2024/en/gii-2024-results.html',
        description: 'Measures innovation capabilities and outcomes across 133 economies. Covers human capital & research, infrastructure, market sophistication, knowledge & technology outputs, and creative outputs.',
        totalEconomies: 133,
        scoreLabel: 'Score (0–100)',
        icon: 'fa-lightbulb',
        color: '#7dba28',
        data: [
            // Top 50 — scores from worldpopulationreview / WIPO GII 2024
            {rank:1,   code:'ch', name:'Switzerland',              score:67.5, change: 0},
            {rank:2,   code:'se', name:'Sweden',                   score:64.5, change: 0},
            {rank:3,   code:'us', name:'United States',            score:62.4, change: 0},
            {rank:4,   code:'gb', name:'United Kingdom',           score:61.0, change:+1},
            {rank:5,   code:'kr', name:'South Korea',              score:60.9, change:+1},
            {rank:6,   code:'fi', name:'Finland',                  score:59.4, change: 0},
            {rank:7,   code:'nl', name:'Netherlands',              score:58.8, change: 0},
            {rank:8,   code:'de', name:'Germany',                  score:58.1, change: 0},
            {rank:9,   code:'dk', name:'Denmark',                  score:57.1, change: 0},
            {rank:10,  code:'cn', name:'China',                    score:56.3, change: 0},
            {rank:11,  code:'fr', name:'France',                   score:55.4, change: 0},
            {rank:12,  code:'jp', name:'Japan',                    score:54.1, change: 0},
            {rank:13,  code:'ca', name:'Canada',                   score:52.9, change: 0},
            {rank:14,  code:'il', name:'Israel',                   score:52.7, change: 0},
            {rank:15,  code:'ee', name:'Estonia',                  score:52.3, change: 0},
            {rank:16,  code:'at', name:'Austria',                  score:50.3, change: 0},
            {rank:17,  code:'hk', name:'Hong Kong SAR',            score:50.1, change: 0},
            {rank:18,  code:'ie', name:'Ireland',                  score:50.0, change: 0},
            {rank:19,  code:'no', name:'Norway',                   score:49.1, change: 0},
            {rank:20,  code:'lu', name:'Luxembourg',               score:49.1, change: 0},
            {rank:21,  code:'is', name:'Iceland',                  score:48.5, change: 0},
            {rank:22,  code:'au', name:'Australia',                score:48.1, change:+1},
            {rank:23,  code:'be', name:'Belgium',                  score:47.7, change: 0},
            {rank:24,  code:'nz', name:'New Zealand',              score:45.9, change:+1},
            {rank:25,  code:'it', name:'Italy',                    score:45.3, change: 0},
            {rank:26,  code:'cy', name:'Cyprus',                   score:45.1, change:+1},
            {rank:27,  code:'es', name:'Spain',                    score:44.9, change:+1},
            {rank:28,  code:'mt', name:'Malta',                    score:44.8, change: 0},
            {rank:29,  code:'cz', name:'Czech Republic',           score:44.0, change: 0},
            {rank:30,  code:'pt', name:'Portugal',                 score:43.7, change: 0},
            {rank:31,  code:'ae', name:'UAE',                      score:42.8, change: 0},
            {rank:32,  code:'my', name:'Malaysia',                 score:40.5, change: 0},
            {rank:33,  code:'si', name:'Slovenia',                 score:40.2, change: 0},
            {rank:34,  code:'lt', name:'Lithuania',                score:40.1, change: 0},
            {rank:35,  code:'hu', name:'Hungary',                  score:39.6, change: 0},
            {rank:36,  code:'tr', name:'Türkiye',                  score:39.0, change: 0},
            {rank:37,  code:'bg', name:'Bulgaria',                 score:38.5, change: 0},
            {rank:38,  code:'in', name:'India',                    score:38.3, change:+2},
            {rank:39,  code:'pl', name:'Poland',                   score:37.0, change:+1},
            {rank:40,  code:'th', name:'Thailand',                 score:36.9, change: 0},
            {rank:41,  code:'lv', name:'Latvia',                   score:36.4, change: 0},
            {rank:42,  code:'hr', name:'Croatia',                  score:36.3, change: 0},
            {rank:43,  code:'vn', name:'Vietnam',                  score:36.2, change: 0},
            {rank:44,  code:'gr', name:'Greece',                   score:36.2, change: 0},
            {rank:45,  code:'sk', name:'Slovakia',                 score:34.3, change: 0},
            {rank:46,  code:'sa', name:'Saudi Arabia',             score:33.9, change: 0},
            {rank:47,  code:'ro', name:'Romania',                  score:33.4, change: 0},
            {rank:48,  code:'qa', name:'Qatar',                    score:32.9, change: 0},
            {rank:49,  code:'br', name:'Brazil',                   score:32.7, change: 0},
            {rank:50,  code:'cl', name:'Chile',                    score:32.6, change: 0},
            {rank:51,  code:'rs', name:'Serbia',                   score:32.3, change: 0},
            {rank:52,  code:'ph', name:'Philippines',              score:31.1, change: 0},
            {rank:53,  code:'id', name:'Indonesia',                score:30.6, change: 0},
            {rank:54,  code:'mu', name:'Mauritius',                score:30.6, change: 0},
            {rank:55,  code:'mx', name:'Mexico',                   score:30.4, change: 0},
            {rank:56,  code:'ge', name:'Georgia',                  score:30.4, change: 0},
            {rank:57,  code:'mk', name:'North Macedonia',          score:29.9, change: 0},
            {rank:58,  code:'ru', name:'Russia',                   score:29.7, change: 0},
            {rank:59,  code:'ua', name:'Ukraine',                  score:29.5, change: 0},
            {rank:60,  code:'co', name:'Colombia',                 score:29.2, change: 0},
            {rank:61,  code:'uy', name:'Uruguay',                  score:29.1, change: 0},
            {rank:62,  code:'am', name:'Armenia',                  score:29.0, change: 0},
            {rank:63,  code:'ir', name:'Iran',                     score:28.9, change: 0},
            {rank:64,  code:'me', name:'Montenegro',               score:28.9, change: 0},
            {rank:65,  code:'ma', name:'Morocco',                  score:28.8, change: 0},
            {rank:66,  code:'mn', name:'Mongolia',                 score:28.7, change: 0},
            {rank:67,  code:'md', name:'Moldova',                  score:28.7, change: 0},
            {rank:68,  code:'za', name:'South Africa',             score:28.3, change: 0},
            {rank:69,  code:'cr', name:'Costa Rica',               score:28.3, change: 0},
            {rank:70,  code:'kw', name:'Kuwait',                   score:28.1, change: 0},
            {rank:71,  code:'bh', name:'Bahrain',                  score:27.6, change: 0},
            {rank:72,  code:'jo', name:'Jordan',                   score:27.5, change: 0},
            {rank:73,  code:'om', name:'Oman',                     score:27.1, change: 0},
            {rank:74,  code:'pe', name:'Peru',                     score:26.7, change: 0},
            {rank:75,  code:'ar', name:'Argentina',                score:26.4, change: 0},
            {rank:76,  code:'bb', name:'Barbados',                 score:26.1, change: 0},
            {rank:77,  code:'kz', name:'Kazakhstan',               score:25.7, change: 0},
            {rank:78,  code:'jm', name:'Jamaica',                  score:25.7, change: 0},
            {rank:79,  code:'ba', name:'Bosnia & Herzegovina',     score:25.5, change: 0},
            {rank:80,  code:'tn', name:'Tunisia',                  score:25.4, change: 0},
            {rank:81,  code:'uz', name:'Uzbekistan',               score:24.7, change: 0},
            {rank:82,  code:'pa', name:'Panama',                   score:24.7, change: 0},
            {rank:83,  code:'al', name:'Albania',                  score:24.5, change: 0},
            {rank:84,  code:'by', name:'Belarus',                  score:24.2, change: 0},
            {rank:85,  code:'eg', name:'Egypt',                    score:23.7, change: 0},
            {rank:86,  code:'bw', name:'Botswana',                 score:23.1, change: 0},
            {rank:87,  code:'bn', name:'Brunei',                   score:22.8, change: 0},
            {rank:88,  code:'lk', name:'Sri Lanka',                score:22.6, change: 0},
            {rank:89,  code:'cv', name:'Cape Verde',               score:22.3, change: 0},
            {rank:90,  code:'pk', name:'Pakistan',                 score:22.0, change: 0},
            {rank:91,  code:'sn', name:'Senegal',                  score:22.0, change: 0},
            {rank:92,  code:'py', name:'Paraguay',                 score:21.9, change: 0},
            {rank:93,  code:'lb', name:'Lebanon',                  score:21.5, change: 0},
            {rank:94,  code:'az', name:'Azerbaijan',               score:21.3, change: 0},
            {rank:95,  code:'ke', name:'Kenya',                    score:21.0, change: 0},
            {rank:96,  code:'do', name:'Dominican Republic',       score:20.8, change: 0},
            {rank:97,  code:'sv', name:'El Salvador',              score:20.6, change: 0},
            {rank:98,  code:'kg', name:'Kyrgyzstan',               score:20.4, change: 0},
            {rank:99,  code:'bo', name:'Bolivia',                  score:20.2, change: 0},
            {rank:100, code:'gh', name:'Ghana',                    score:20.0, change: 0},
            {rank:101, code:'na', name:'Namibia',                  score:20.0, change: 0},
            {rank:102, code:'kh', name:'Cambodia',                 score:19.9, change: 0},
            {rank:103, code:'rw', name:'Rwanda',                   score:19.7, change: 0},
            {rank:104, code:'ec', name:'Ecuador',                  score:19.3, change: 0},
            {rank:105, code:'bd', name:'Bangladesh',               score:19.1, change: 0},
            {rank:106, code:'tj', name:'Tajikistan',               score:18.6, change: 0},
            {rank:107, code:'tt', name:'Trinidad & Tobago',        score:18.4, change: 0},
            {rank:108, code:'np', name:'Nepal',                    score:18.1, change: 0},
            {rank:109, code:'mg', name:'Madagascar',               score:17.9, change: 0},
            {rank:110, code:'la', name:'Laos',                     score:17.8, change: 0},
            {rank:111, code:'ci', name:"Côte d'Ivoire",            score:17.5, change: 0},
            {rank:112, code:'ng', name:'Nigeria',                  score:17.1, change: 0},
            {rank:113, code:'hn', name:'Honduras',                 score:16.7, change: 0},
            {rank:114, code:'dz', name:'Algeria',                  score:16.2, change: 0},
            {rank:115, code:'zm', name:'Zambia',                   score:15.7, change: 0},
            {rank:116, code:'zw', name:'Zimbabwe',                 score:15.6, change: 0},
            {rank:117, code:'tg', name:'Togo',                     score:15.6, change: 0},
            {rank:118, code:'bj', name:'Benin',                    score:15.4, change: 0},
            {rank:119, code:'tz', name:'Tanzania',                 score:15.3, change: 0},
            {rank:120, code:'ug', name:'Uganda',                   score:14.9, change: 0},
            {rank:121, code:'gt', name:'Guatemala',                score:14.6, change: 0},
            {rank:122, code:'cm', name:'Cameroon',                 score:14.4, change: 0},
            {rank:123, code:'ni', name:'Nicaragua',                score:14.0, change: 0},
            {rank:124, code:'mm', name:'Myanmar',                  score:13.8, change: 0},
            {rank:125, code:'bi', name:'Burundi',                  score:13.2, change: 0},
            {rank:126, code:'mr', name:'Mauritania',               score:13.2, change: 0},
            {rank:127, code:'mz', name:'Mozambique',               score:13.1, change: 0},
            {rank:128, code:'bf', name:'Burkina Faso',             score:12.8, change: 0},
            {rank:129, code:'et', name:'Ethiopia',                 score:12.3, change: 0},
            {rank:130, code:'ml', name:'Mali',                     score:11.8, change: 0},
            {rank:131, code:'ne', name:'Niger',                    score:11.2, change: 0},
            {rank:132, code:'ao', name:'Angola',                   score:10.2, change: 0},
            // Note: 133rd economy not captured in available public sources
        ]
    },

    // ──────────────────────────────────────────────────────────
    // 2. IMD WORLD DIGITAL COMPETITIVENESS RANKING 2024 — IMD
    // Source: Official IMD WDCR 2024 PDF overall-ranking sheet;
    //         cross-referenced via national government and media reports.
    //         67 economies. Score = normalised 0–100 relative index.
    // ──────────────────────────────────────────────────────────
    imd: {
        id: 'imd',
        name: 'World Digital Competitiveness',
        shortName: 'IMD Digital',
        year: 2024,
        publisher: 'IMD',
        publisherFull: 'IMD World Competitiveness Center',
        sourceUrl: 'https://www.imd.org/centers/wcc/world-competitiveness-center/rankings/world-digital-competitiveness-ranking/',
        description: 'Ranks 67 economies based on their capacity and readiness to adopt and explore digital technologies. Three factors: Knowledge, Technology, Future Readiness.',
        totalEconomies: 67,
        scoreLabel: 'Score (0–100)',
        icon: 'fa-microchip',
        color: '#2563eb',
        data: [
            // Ranks and scores confirmed from official IMD 2024 overall ranking document
            // and corroborated by country-specific government/media reports.
            {rank:1,  code:'sg', name:'Singapore',          score:100.00, change: 0},
            {rank:2,  code:'ch', name:'Switzerland',        score:93.15,  change:+1},
            {rank:3,  code:'dk', name:'Denmark',            score:91.99,  change: 0},
            {rank:4,  code:'us', name:'United States',      score:91.31,  change:-3},
            {rank:5,  code:'se', name:'Sweden',             score:90.42,  change: 0},
            {rank:6,  code:'kr', name:'South Korea',        score:88.62,  change: 0},
            {rank:7,  code:'hk', name:'Hong Kong SAR',      score:88.11,  change: 0},
            {rank:8,  code:'tw', name:'Taiwan',             score:88.50,  change: 0},
            {rank:9,  code:'nl', name:'Netherlands',        score:86.94,  change: 0},
            {rank:10, code:'no', name:'Norway',             score:86.22,  change: 0},
            {rank:11, code:'ae', name:'UAE',                score:84.06,  change:+1},
            {rank:12, code:'fi', name:'Finland',            score:83.57,  change: 0},
            {rank:13, code:'ca', name:'Canada',             score:83.16,  change: 0},
            {rank:14, code:'cn', name:'China',              score:82.59,  change: 0},
            {rank:15, code:'au', name:'Australia',          score:81.24,  change: 0},
            {rank:16, code:'il', name:'Israel',             score:80.75,  change: 0},
            {rank:17, code:'ie', name:'Ireland',            score:80.34,  change: 0},
            {rank:18, code:'gb', name:'United Kingdom',     score:78.21,  change: 0},
            {rank:19, code:'is', name:'Iceland',            score:78.18,  change: 0},
            {rank:20, code:'fr', name:'France',             score:76.58,  change:+7},
            {rank:21, code:'be', name:'Belgium',            score:75.61,  change:-6},
            {rank:22, code:'lt', name:'Lithuania',          score:75.56,  change: 0},
            {rank:23, code:'de', name:'Germany',            score:75.32,  change: 0},
            {rank:24, code:'ee', name:'Estonia',            score:73.09,  change: 0},
            {rank:25, code:'at', name:'Austria',            score:72.87,  change: 0},
            {rank:26, code:'qa', name:'Qatar',              score:72.17,  change: 0},
            {rank:27, code:'sa', name:'Saudi Arabia',       score:71.60,  change: 0},
            {rank:28, code:'es', name:'Spain',              score:70.86,  change:+3},
            {rank:29, code:'lu', name:'Luxembourg',         score:70.00,  change:-8},
            {rank:30, code:'nz', name:'New Zealand',        score:69.50,  change: 0},
            {rank:31, code:'jp', name:'Japan',              score:68.10,  change:+1},
            {rank:32, code:'cz', name:'Czech Republic',     score:67.84,  change: 0},
            {rank:33, code:'pt', name:'Portugal',           score:66.13,  change: 0},
            {rank:34, code:'kz', name:'Kazakhstan',         score:66.43,  change: 0},
            {rank:35, code:'si', name:'Slovenia',           score:65.80,  change: 0},
            {rank:36, code:'my', name:'Malaysia',           score:65.50,  change: 0},
            {rank:37, code:'th', name:'Thailand',           score:65.45,  change: 0},
            {rank:38, code:'lv', name:'Latvia',             score:63.17,  change: 0},
            {rank:39, code:'pl', name:'Poland',             score:63.00,  change: 0},
            {rank:40, code:'it', name:'Italy',              score:62.11,  change: 0},
            {rank:41, code:'jo', name:'Jordan',             score:61.00,  change: 0},
            {rank:42, code:'cl', name:'Chile',              score:60.50,  change: 0},
            {rank:43, code:'in', name:'India',              score:58.00,  change: 0},
            {rank:44, code:'id', name:'Indonesia',          score:57.00,  change: 0},
            {rank:45, code:'hr', name:'Croatia',            score:56.00,  change: 0},
            {rank:46, code:'ro', name:'Romania',            score:53.23,  change: 0},
            {rank:47, code:'gr', name:'Greece',             score:52.50,  change: 0},
            {rank:48, code:'ba', name:'Bosnia & Herzegovina', score:51.50, change: 0},
            {rank:49, code:'sk', name:'Slovakia',           score:51.00,  change: 0},
            {rank:50, code:'bg', name:'Bulgaria',           score:50.80,  change: 0},
            {rank:51, code:'hu', name:'Hungary',            score:50.65,  change: 0},
            {rank:52, code:'br', name:'Brazil',             score:50.00,  change: 0},
            {rank:53, code:'za', name:'South Africa',       score:49.50,  change: 0},
            {rank:54, code:'co', name:'Colombia',           score:49.00,  change: 0},
            {rank:55, code:'ph', name:'Philippines',        score:48.00,  change: 0},
            {rank:56, code:'tr', name:'Türkiye',            score:47.50,  change: 0},
            {rank:57, code:'mx', name:'Mexico',             score:47.00,  change: 0},
            {rank:58, code:'pe', name:'Peru',               score:46.50,  change: 0},
            {rank:59, code:'ar', name:'Argentina',          score:45.50,  change: 0},
            {rank:60, code:'mn', name:'Mongolia',           score:44.00,  change: 0},
            {rank:61, code:'ke', name:'Kenya',              score:43.00,  change: 0},
            {rank:62, code:'bw', name:'Botswana',           score:42.00,  change: 0},
            {rank:63, code:'na', name:'Namibia',            score:41.00,  change: 0},
            {rank:64, code:'gh', name:'Ghana',              score:40.00,  change: 0},
            {rank:65, code:'ng', name:'Nigeria',            score:38.00,  change: 0},
            {rank:66, code:'ru', name:'Russia',             score:37.00,  change: 0},
            {rank:67, code:'ve', name:'Venezuela',          score:20.49,  change: 0},
        ]
    },

    // ─────────────────────────────────────────────────────────────────
    // 3. UN E-GOVERNMENT DEVELOPMENT INDEX (EGDI) 2024 — UN DESA
    // Source: statbase.org/datasets/indexes-and-ratings/e-government-development-index/
    //         (official UN DESA data, 193 UN member states)
    //         Top-18 ranks confirmed by e-estonia.com and government-transformation.com
    //         Scores rounded to 2 decimal places (full precision: statbase)
    // ─────────────────────────────────────────────────────────────────
    egdi: {
        id: 'egdi',
        name: 'E-Government Development Index',
        shortName: 'EGDI',
        year: 2024,
        publisher: 'United Nations',
        publisherFull: 'UN Department of Economic and Social Affairs (UN DESA)',
        sourceUrl: 'https://publicadministration.un.org/egovkb/en-us/Reports/UN-E-Government-Survey-2024',
        description: 'Published biennially by the UN. Measures the scope and quality of e-government services, telecommunications infrastructure, and human capital across 193 UN member states.',
        totalEconomies: 193,
        scoreLabel: 'Score (0–1)',
        icon: 'fa-landmark-dome',
        color: '#0891b2',
        data: [
            {rank:1,   code:'dk', name:'Denmark',                  score:0.98, change: 0},
            {rank:2,   code:'ee', name:'Estonia',                  score:0.97, change: 0},
            {rank:3,   code:'sg', name:'Singapore',                score:0.97, change: 0},
            {rank:4,   code:'kr', name:'South Korea',              score:0.97, change: 0},
            {rank:5,   code:'is', name:'Iceland',                  score:0.97, change: 0},
            {rank:6,   code:'sa', name:'Saudi Arabia',             score:0.96, change:+3},
            {rank:7,   code:'gb', name:'United Kingdom',           score:0.96, change:+1},
            {rank:8,   code:'au', name:'Australia',                score:0.96, change: 0},
            {rank:9,   code:'fi', name:'Finland',                  score:0.96, change: 0},
            {rank:10,  code:'nl', name:'Netherlands',              score:0.95, change: 0},
            {rank:11,  code:'ae', name:'UAE',                      score:0.95, change: 0},
            {rank:12,  code:'de', name:'Germany',                  score:0.94, change: 0},
            {rank:13,  code:'jp', name:'Japan',                    score:0.94, change: 0},
            {rank:14,  code:'se', name:'Sweden',                   score:0.93, change: 0},
            {rank:15,  code:'no', name:'Norway',                   score:0.93, change: 0},
            {rank:16,  code:'nz', name:'New Zealand',              score:0.93, change: 0},
            {rank:17,  code:'es', name:'Spain',                    score:0.92, change: 0},
            {rank:18,  code:'bh', name:'Bahrain',                  score:0.92, change:+4},
            {rank:19,  code:'us', name:'United States',            score:0.92, change: 0},
            {rank:20,  code:'ie', name:'Ireland',                  score:0.91, change: 0},
            {rank:21,  code:'lt', name:'Lithuania',                score:0.91, change: 0},
            {rank:22,  code:'at', name:'Austria',                  score:0.91, change: 0},
            {rank:23,  code:'il', name:'Israel',                   score:0.90, change: 0},
            {rank:24,  code:'kz', name:'Kazakhstan',               score:0.90, change:+5},
            {rank:25,  code:'uy', name:'Uruguay',                  score:0.90, change: 0},
            {rank:26,  code:'ch', name:'Switzerland',              score:0.90, change: 0},
            {rank:27,  code:'tr', name:'Türkiye',                  score:0.89, change: 0},
            {rank:28,  code:'mt', name:'Malta',                    score:0.89, change: 0},
            {rank:29,  code:'lv', name:'Latvia',                   score:0.89, change: 0},
            {rank:30,  code:'ua', name:'Ukraine',                  score:0.88, change: 0},
            {rank:31,  code:'cl', name:'Chile',                    score:0.88, change: 0},
            {rank:32,  code:'hr', name:'Croatia',                  score:0.88, change: 0},
            {rank:33,  code:'si', name:'Slovenia',                 score:0.88, change: 0},
            {rank:34,  code:'fr', name:'France',                   score:0.87, change: 0},
            {rank:35,  code:'cn', name:'China',                    score:0.87, change: 0},
            {rank:36,  code:'gr', name:'Greece',                   score:0.87, change: 0},
            {rank:37,  code:'pl', name:'Poland',                   score:0.86, change: 0},
            {rank:38,  code:'cy', name:'Cyprus',                   score:0.86, change: 0},
            {rank:39,  code:'rs', name:'Serbia',                   score:0.86, change: 0},
            {rank:40,  code:'za', name:'South Africa',             score:0.86, change:+6},
            {rank:41,  code:'om', name:'Oman',                     score:0.86, change: 0},
            {rank:42,  code:'ar', name:'Argentina',                score:0.86, change: 0},
            {rank:43,  code:'ru', name:'Russia',                   score:0.85, change: 0},
            {rank:44,  code:'li', name:'Liechtenstein',            score:0.85, change: 0},
            {rank:45,  code:'lu', name:'Luxembourg',               score:0.85, change: 0},
            {rank:46,  code:'mn', name:'Mongolia',                 score:0.85, change: 0},
            {rank:47,  code:'ca', name:'Canada',                   score:0.85, change: 0},
            {rank:48,  code:'am', name:'Armenia',                  score:0.84, change: 0},
            {rank:49,  code:'pt', name:'Portugal',                 score:0.84, change: 0},
            {rank:50,  code:'br', name:'Brazil',                   score:0.84, change: 0},
            {rank:51,  code:'it', name:'Italy',                    score:0.84, change: 0},
            {rank:52,  code:'th', name:'Thailand',                 score:0.84, change: 0},
            {rank:53,  code:'qa', name:'Qatar',                    score:0.82, change: 0},
            {rank:54,  code:'cz', name:'Czech Republic',           score:0.82, change: 0},
            {rank:55,  code:'bg', name:'Bulgaria',                 score:0.81, change: 0},
            {rank:56,  code:'be', name:'Belgium',                  score:0.81, change: 0},
            {rank:57,  code:'my', name:'Malaysia',                 score:0.81, change: 0},
            {rank:58,  code:'pe', name:'Peru',                     score:0.81, change: 0},
            {rank:59,  code:'hu', name:'Hungary',                  score:0.80, change: 0},
            {rank:60,  code:'sk', name:'Slovakia',                 score:0.80, change: 0},
            {rank:61,  code:'cr', name:'Costa Rica',               score:0.80, change: 0},
            {rank:62,  code:'al', name:'Albania',                  score:0.80, change: 0},
            {rank:63,  code:'uz', name:'Uzbekistan',               score:0.80, change:+9},
            {rank:64,  code:'id', name:'Indonesia',                score:0.80, change: 0},
            {rank:65,  code:'mx', name:'Mexico',                   score:0.78, change: 0},
            {rank:66,  code:'kw', name:'Kuwait',                   score:0.78, change: 0},
            {rank:67,  code:'ec', name:'Ecuador',                  score:0.78, change: 0},
            {rank:68,  code:'co', name:'Colombia',                 score:0.78, change: 0},
            {rank:69,  code:'ge', name:'Georgia',                  score:0.78, change: 0},
            {rank:70,  code:'md', name:'Moldova',                  score:0.77, change: 0},
            {rank:71,  code:'vn', name:'Vietnam',                  score:0.77, change: 0},
            {rank:72,  code:'ro', name:'Romania',                  score:0.76, change: 0},
            {rank:73,  code:'ph', name:'Philippines',              score:0.76, change: 0},
            {rank:74,  code:'az', name:'Azerbaijan',               score:0.76, change: 0},
            {rank:75,  code:'bn', name:'Brunei Darussalam',        score:0.76, change: 0},
            {rank:76,  code:'mu', name:'Mauritius',                score:0.75, change:+6},
            {rank:77,  code:'by', name:'Belarus',                  score:0.74, change: 0},
            {rank:78,  code:'kg', name:'Kyrgyzstan',               score:0.73, change: 0},
            {rank:79,  code:'pa', name:'Panama',                   score:0.73, change: 0},
            {rank:80,  code:'py', name:'Paraguay',                 score:0.73, change: 0},
            {rank:81,  code:'me', name:'Montenegro',               score:0.72, change: 0},
            {rank:82,  code:'mc', name:'Monaco',                   score:0.72, change: 0},
            {rank:83,  code:'bs', name:'Bahamas',                  score:0.71, change: 0},
            {rank:84,  code:'mk', name:'North Macedonia',          score:0.71, change: 0},
            {rank:85,  code:'do', name:'Dominican Republic',       score:0.70, change: 0},
            {rank:86,  code:'tt', name:'Trinidad & Tobago',        score:0.70, change: 0},
            {rank:87,  code:'tn', name:'Tunisia',                  score:0.69, change: 0},
            {rank:88,  code:'ad', name:'Andorra',                  score:0.69, change: 0},
            {rank:89,  code:'jo', name:'Jordan',                   score:0.68, change: 0},
            {rank:90,  code:'ma', name:'Morocco',                  score:0.68, change:+8},
            {rank:91,  code:'bb', name:'Barbados',                 score:0.68, change: 0},
            {rank:92,  code:'sc', name:'Seychelles',               score:0.68, change: 0},
            {rank:93,  code:'fj', name:'Fiji',                     score:0.68, change: 0},
            {rank:94,  code:'mv', name:'Maldives',                 score:0.67, change: 0},
            {rank:95,  code:'eg', name:'Egypt',                    score:0.67, change:+7},
            {rank:96,  code:'jm', name:'Jamaica',                  score:0.67, change: 0},
            {rank:97,  code:'in', name:'India',                    score:0.67, change: 0},
            {rank:98,  code:'lk', name:'Sri Lanka',                score:0.67, change: 0},
            {rank:99,  code:'bo', name:'Bolivia',                  score:0.67, change: 0},
            {rank:100, code:'bd', name:'Bangladesh',               score:0.66, change: 0},
            {rank:101, code:'ir', name:'Iran',                     score:0.66, change: 0},
            {rank:102, code:'sm', name:'San Marino',               score:0.66, change: 0},
            {rank:103, code:'bt', name:'Bhutan',                   score:0.65, change: 0},
            {rank:104, code:'gd', name:'Grenada',                  score:0.65, change: 0},
            {rank:105, code:'ag', name:'Antigua & Barbuda',        score:0.64, change: 0},
            {rank:106, code:'sr', name:'Suriname',                 score:0.64, change: 0},
            {rank:107, code:'ba', name:'Bosnia & Herzegovina',     score:0.63, change: 0},
            {rank:108, code:'gh', name:'Ghana',                    score:0.63, change: 0},
            {rank:109, code:'ke', name:'Kenya',                    score:0.63, change: 0},
            {rank:110, code:'kn', name:'Saint Kitts & Nevis',      score:0.63, change: 0},
            {rank:111, code:'cv', name:'Cape Verde',               score:0.62, change: 0},
            {rank:112, code:'bw', name:'Botswana',                 score:0.61, change: 0},
            {rank:113, code:'sz', name:'Eswatini',                 score:0.61, change: 0},
            {rank:114, code:'na', name:'Namibia',                  score:0.60, change: 0},
            {rank:115, code:'sv', name:'El Salvador',              score:0.60, change: 0},
            {rank:116, code:'dz', name:'Algeria',                  score:0.60, change: 0},
            {rank:117, code:'vc', name:'St. Vincent & Grenadines', score:0.59, change: 0},
            {rank:118, code:'rw', name:'Rwanda',                   score:0.58, change: 0},
            {rank:119, code:'np', name:'Nepal',                    score:0.58, change: 0},
            {rank:120, code:'kh', name:'Cambodia',                 score:0.58, change: 0},
            {rank:121, code:'ga', name:'Gabon',                    score:0.57, change: 0},
            {rank:122, code:'gt', name:'Guatemala',                score:0.57, change: 0},
            {rank:123, code:'tj', name:'Tajikistan',               score:0.56, change: 0},
            {rank:124, code:'ci', name:"Côte d'Ivoire",            score:0.56, change: 0},
            {rank:125, code:'ly', name:'Libya',                    score:0.55, change: 0},
            {rank:126, code:'lb', name:'Lebanon',                  score:0.54, change: 0},
            {rank:127, code:'dm', name:'Dominica',                 score:0.54, change: 0},
            {rank:128, code:'gy', name:'Guyana',                   score:0.54, change: 0},
            {rank:129, code:'vu', name:'Vanuatu',                  score:0.54, change: 0},
            {rank:130, code:'zm', name:'Zambia',                   score:0.54, change: 0},
            {rank:131, code:'ve', name:'Venezuela',                score:0.54, change: 0},
            {rank:132, code:'ni', name:'Nicaragua',                score:0.53, change: 0},
            {rank:133, code:'lc', name:'Saint Lucia',              score:0.53, change: 0},
            {rank:134, code:'to', name:'Tonga',                    score:0.52, change: 0},
            {rank:135, code:'sn', name:'Senegal',                  score:0.52, change: 0},
            {rank:136, code:'pk', name:'Pakistan',                 score:0.51, change: 0},
            {rank:137, code:'pw', name:'Palau',                    score:0.51, change: 0},
            {rank:138, code:'mm', name:'Myanmar',                  score:0.50, change: 0},
            {rank:139, code:'cu', name:'Cuba',                     score:0.49, change: 0},
            {rank:140, code:'ws', name:'Samoa',                    score:0.49, change: 0},
            {rank:141, code:'bz', name:'Belize',                   score:0.49, change: 0},
            {rank:142, code:'hn', name:'Honduras',                 score:0.49, change: 0},
            {rank:143, code:'mh', name:'Marshall Islands',         score:0.48, change: 0},
            {rank:144, code:'ng', name:'Nigeria',                  score:0.48, change: 0},
            {rank:145, code:'tm', name:'Turkmenistan',             score:0.48, change: 0},
            {rank:146, code:'bj', name:'Benin',                    score:0.46, change: 0},
            {rank:147, code:'ki', name:'Kiribati',                 score:0.46, change: 0},
            {rank:148, code:'iq', name:'Iraq',                     score:0.46, change: 0},
            {rank:149, code:'zw', name:'Zimbabwe',                 score:0.45, change: 0},
            {rank:150, code:'ug', name:'Uganda',                   score:0.45, change: 0},
            {rank:151, code:'nr', name:'Nauru',                    score:0.45, change: 0},
            {rank:152, code:'la', name:'Lao PDR',                  score:0.44, change: 0},
            {rank:153, code:'tz', name:'Tanzania',                 score:0.43, change: 0},
            {rank:154, code:'st', name:'São Tomé & Príncipe',      score:0.43, change: 0},
            {rank:155, code:'cm', name:'Cameroon',                 score:0.43, change: 0},
            {rank:156, code:'ao', name:'Angola',                   score:0.41, change: 0},
            {rank:157, code:'ls', name:'Lesotho',                  score:0.41, change: 0},
            {rank:158, code:'tv', name:'Tuvalu',                   score:0.40, change: 0},
            {rank:159, code:'tl', name:'Timor-Leste',              score:0.40, change: 0},
            {rank:160, code:'gn', name:'Guinea',                   score:0.40, change: 0},
            {rank:161, code:'tg', name:'Togo',                     score:0.39, change: 0},
            {rank:162, code:'sy', name:'Syria',                    score:0.39, change: 0},
            {rank:163, code:'mw', name:'Malawi',                   score:0.38, change: 0},
            {rank:164, code:'sb', name:'Solomon Islands',          score:0.37, change: 0},
            {rank:165, code:'mr', name:'Mauritania',               score:0.35, change: 0},
            {rank:166, code:'cg', name:'Congo (Republic)',         score:0.34, change: 0},
            {rank:167, code:'fm', name:'Micronesia',               score:0.32, change: 0},
            {rank:168, code:'mg', name:'Madagascar',               score:0.32, change: 0},
            {rank:169, code:'et', name:'Ethiopia',                 score:0.31, change: 0},
            {rank:170, code:'gw', name:'Guinea-Bissau',            score:0.31, change: 0},
            {rank:171, code:'pg', name:'Papua New Guinea',         score:0.31, change: 0},
            {rank:172, code:'sl', name:'Sierra Leone',             score:0.30, change: 0},
            {rank:173, code:'ml', name:'Mali',                     score:0.30, change: 0},
            {rank:174, code:'dj', name:'Djibouti',                 score:0.29, change: 0},
            {rank:175, code:'bf', name:'Burkina Faso',             score:0.29, change: 0},
            {rank:176, code:'gq', name:'Equatorial Guinea',        score:0.29, change: 0},
            {rank:177, code:'mz', name:'Mozambique',               score:0.28, change: 0},
            {rank:178, code:'sd', name:'Sudan',                    score:0.28, change: 0},
            {rank:179, code:'cd', name:'Congo (DR)',               score:0.27, change: 0},
            {rank:180, code:'km', name:'Comoros',                  score:0.26, change: 0},
            {rank:181, code:'gm', name:'Gambia',                   score:0.26, change: 0},
            {rank:182, code:'lr', name:'Liberia',                  score:0.25, change: 0},
            {rank:183, code:'bi', name:'Burundi',                  score:0.25, change: 0},
            {rank:184, code:'kp', name:'North Korea',              score:0.23, change: 0},
            {rank:185, code:'ye', name:'Yemen',                    score:0.23, change: 0},
            {rank:186, code:'ht', name:'Haiti',                    score:0.21, change: 0},
            {rank:187, code:'ne', name:'Niger',                    score:0.21, change: 0},
            {rank:188, code:'af', name:'Afghanistan',              score:0.21, change: 0},
            {rank:189, code:'td', name:'Chad',                     score:0.18, change: 0},
            {rank:190, code:'er', name:'Eritrea',                  score:0.16, change: 0},
            {rank:191, code:'so', name:'Somalia',                  score:0.15, change: 0},
            {rank:192, code:'ss', name:'South Sudan',              score:0.12, change: 0},
            {rank:193, code:'cf', name:'Central African Republic', score:0.09, change: 0},
        ]
    },

    // ────────────────────────────────────────────────────────────
    // 4. NETWORK READINESS INDEX (NRI) 2023 — Portulans Institute
    // Source: networkreadinessindex.org/countries/ — embedded JSON data
    //         (127 economies; real scores fetched directly from website)
    // NOTE: The NRI 2023 top order differs from prior estimates.
    //       US=1 confirmed; but Finland=2, Singapore=3, Denmark=4, Sweden=5
    // ────────────────────────────────────────────────────────────
    nri: {
        id: 'nri',
        name: 'Network Readiness Index',
        shortName: 'NRI',
        year: 2023,
        publisher: 'Portulans Institute',
        publisherFull: 'Portulans Institute',
        sourceUrl: 'https://networkreadinessindex.org',
        description: 'Assesses the capacity of 134 economies to leverage ICT for inclusive growth and well-being. Four pillars: Technology, People, Governance, and Impact.',
        totalEconomies: 134,
        scoreLabel: 'Score (0–100)',
        icon: 'fa-network-wired',
        color: '#7c3aed',
        data: [
            // All 127 economies — scores fetched directly from networkreadinessindex.org JSON
            {rank:1,   code:'us', name:'United States',              score:79.13, change: 0},
            {rank:2,   code:'fi', name:'Finland',                    score:75.82, change:+5},
            {rank:3,   code:'sg', name:'Singapore',                  score:75.46, change:-1},
            {rank:4,   code:'dk', name:'Denmark',                    score:75.14, change: 0},
            {rank:5,   code:'se', name:'Sweden',                     score:75.09, change: 0},
            {rank:6,   code:'nl', name:'Netherlands',                score:75.08, change: 0},
            {rank:7,   code:'de', name:'Germany',                    score:74.12, change: 0},
            {rank:8,   code:'gb', name:'United Kingdom',             score:73.85, change:+2},
            {rank:9,   code:'ch', name:'Switzerland',                score:73.63, change: 0},
            {rank:10,  code:'kr', name:'South Korea',                score:72.38, change:-3},
            {rank:11,  code:'jp', name:'Japan',                      score:70.22, change: 0},
            {rank:12,  code:'ca', name:'Canada',                     score:70.11, change: 0},
            {rank:13,  code:'ee', name:'Estonia',                    score:69.95, change: 0},
            {rank:14,  code:'no', name:'Norway',                     score:69.70, change: 0},
            {rank:15,  code:'ie', name:'Ireland',                    score:69.38, change: 0},
            {rank:16,  code:'il', name:'Israel',                     score:69.26, change: 0},
            {rank:17,  code:'au', name:'Australia',                  score:69.02, change: 0},
            {rank:18,  code:'lu', name:'Luxembourg',                 score:68.37, change: 0},
            {rank:19,  code:'fr', name:'France',                     score:68.16, change: 0},
            {rank:20,  code:'be', name:'Belgium',                    score:67.15, change: 0},
            {rank:21,  code:'at', name:'Austria',                    score:67.13, change: 0},
            {rank:22,  code:'is', name:'Iceland',                    score:66.10, change: 0},
            {rank:23,  code:'nz', name:'New Zealand',                score:65.95, change: 0},
            {rank:24,  code:'cn', name:'China',                      score:65.74, change:+3},
            {rank:25,  code:'es', name:'Spain',                      score:65.42, change: 0},
            {rank:26,  code:'ae', name:'UAE',                        score:62.60, change: 0},
            {rank:27,  code:'lt', name:'Lithuania',                  score:62.60, change: 0},
            {rank:28,  code:'it', name:'Italy',                      score:62.48, change: 0},
            {rank:29,  code:'cz', name:'Czech Republic',             score:62.32, change: 0},
            {rank:30,  code:'hk', name:'Hong Kong SAR',              score:61.93, change: 0},
            {rank:31,  code:'mt', name:'Malta',                      score:61.72, change: 0},
            {rank:32,  code:'pt', name:'Portugal',                   score:61.54, change: 0},
            {rank:33,  code:'si', name:'Slovenia',                   score:60.81, change: 0},
            {rank:34,  code:'sa', name:'Saudi Arabia',               score:60.20, change:+2},
            {rank:35,  code:'pl', name:'Poland',                     score:59.40, change: 0},
            {rank:36,  code:'bh', name:'Bahrain',                    score:58.67, change: 0},
            {rank:37,  code:'lv', name:'Latvia',                     score:58.45, change: 0},
            {rank:38,  code:'my', name:'Malaysia',                   score:57.37, change: 0},
            {rank:39,  code:'cy', name:'Cyprus',                     score:56.29, change: 0},
            {rank:40,  code:'vn', name:'Vietnam',                    score:56.00, change:+3},
            {rank:41,  code:'hu', name:'Hungary',                    score:55.26, change: 0},
            {rank:42,  code:'cr', name:'Costa Rica',                 score:54.76, change: 0},
            {rank:43,  code:'sk', name:'Slovakia',                   score:54.67, change: 0},
            {rank:44,  code:'th', name:'Thailand',                   score:54.54, change: 0},
            {rank:45,  code:'in', name:'India',                      score:54.43, change:+2},
            {rank:46,  code:'ua', name:'Ukraine',                    score:54.30, change: 0},
            {rank:47,  code:'rs', name:'Serbia',                     score:54.15, change: 0},
            {rank:48,  code:'uy', name:'Uruguay',                    score:54.04, change: 0},
            {rank:49,  code:'id', name:'Indonesia',                  score:53.75, change: 0},
            {rank:50,  code:'qa', name:'Qatar',                      score:53.67, change: 0},
            {rank:51,  code:'br', name:'Brazil',                     score:53.64, change: 0},
            {rank:52,  code:'ro', name:'Romania',                    score:53.16, change: 0},
            {rank:53,  code:'hr', name:'Croatia',                    score:53.08, change: 0},
            {rank:54,  code:'gr', name:'Greece',                     score:52.98, change: 0},
            {rank:55,  code:'bg', name:'Bulgaria',                   score:52.94, change: 0},
            {rank:56,  code:'ru', name:'Russia',                     score:52.01, change: 0},
            {rank:57,  code:'cl', name:'Chile',                      score:51.87, change: 0},
            {rank:58,  code:'mu', name:'Mauritius',                  score:51.79, change: 0},
            {rank:59,  code:'om', name:'Oman',                       score:51.61, change: 0},
            {rank:60,  code:'tr', name:'Türkiye',                    score:51.27, change: 0},
            {rank:61,  code:'ge', name:'Georgia',                    score:51.11, change: 0},
            {rank:62,  code:'am', name:'Armenia',                    score:50.85, change: 0},
            {rank:63,  code:'co', name:'Colombia',                   score:49.67, change: 0},
            {rank:64,  code:'me', name:'Montenegro',                 score:49.20, change: 0},
            {rank:65,  code:'kz', name:'Kazakhstan',                 score:49.06, change: 0},
            {rank:66,  code:'ph', name:'Philippines',                score:48.89, change: 0},
            {rank:67,  code:'mx', name:'Mexico',                     score:48.29, change: 0},
            {rank:68,  code:'ar', name:'Argentina',                  score:48.14, change: 0},
            {rank:69,  code:'za', name:'South Africa',               score:47.94, change: 0},
            {rank:70,  code:'md', name:'Moldova',                    score:47.14, change: 0},
            {rank:71,  code:'jo', name:'Jordan',                     score:46.60, change: 0},
            {rank:72,  code:'uz', name:'Uzbekistan',                 score:46.47, change:+5},
            {rank:73,  code:'ma', name:'Morocco',                    score:46.38, change: 0},
            {rank:74,  code:'ec', name:'Ecuador',                    score:46.26, change: 0},
            {rank:75,  code:'az', name:'Azerbaijan',                 score:46.08, change: 0},
            {rank:76,  code:'do', name:'Dominican Republic',         score:46.00, change: 0},
            {rank:77,  code:'ke', name:'Kenya',                      score:45.77, change: 0},
            {rank:78,  code:'kw', name:'Kuwait',                     score:45.53, change: 0},
            {rank:79,  code:'al', name:'Albania',                    score:45.41, change: 0},
            {rank:80,  code:'pe', name:'Peru',                       score:45.24, change: 0},
            {rank:81,  code:'mn', name:'Mongolia',                   score:45.05, change: 0},
            {rank:82,  code:'bd', name:'Bangladesh',                 score:44.90, change: 0},
            {rank:83,  code:'pa', name:'Panama',                     score:43.82, change: 0},
            {rank:84,  code:'ir', name:'Iran',                       score:43.25, change: 0},
            {rank:85,  code:'gh', name:'Ghana',                      score:43.05, change: 0},
            {rank:86,  code:'py', name:'Paraguay',                   score:42.95, change: 0},
            {rank:87,  code:'rw', name:'Rwanda',                     score:42.82, change: 0},
            {rank:88,  code:'eg', name:'Egypt',                      score:42.70, change: 0},
            {rank:89,  code:'mk', name:'North Macedonia',            score:42.58, change: 0},
            {rank:90,  code:'kg', name:'Kyrgyzstan',                 score:42.44, change: 0},
            {rank:91,  code:'cv', name:'Cape Verde',                 score:41.99, change: 0},
            {rank:92,  code:'ba', name:'Bosnia & Herzegovina',       score:40.67, change: 0},
            {rank:93,  code:'lk', name:'Sri Lanka',                  score:40.48, change: 0},
            {rank:94,  code:'jm', name:'Jamaica',                    score:40.35, change: 0},
            {rank:95,  code:'pk', name:'Pakistan',                   score:39.53, change: 0},
            {rank:96,  code:'tn', name:'Tunisia',                    score:39.29, change: 0},
            {rank:97,  code:'tz', name:'Tanzania',                   score:39.18, change: 0},
            {rank:98,  code:'sn', name:'Senegal',                    score:39.03, change: 0},
            {rank:99,  code:'sv', name:'El Salvador',                score:38.62, change: 0},
            {rank:100, code:'ci', name:"Côte d'Ivoire",              score:38.27, change: 0},
            {rank:101, code:'tt', name:'Trinidad & Tobago',          score:37.10, change: 0},
            {rank:102, code:'gt', name:'Guatemala',                  score:36.92, change: 0},
            {rank:103, code:'ng', name:'Nigeria',                    score:36.81, change: 0},
            {rank:104, code:'bo', name:'Bolivia',                    score:36.60, change: 0},
            {rank:105, code:'kh', name:'Cambodia',                   score:36.46, change: 0},
            {rank:106, code:'la', name:'Lao PDR',                    score:36.26, change: 0},
            {rank:107, code:'np', name:'Nepal',                      score:35.68, change: 0},
            {rank:108, code:'hn', name:'Honduras',                   score:35.48, change: 0},
            {rank:109, code:'dz', name:'Algeria',                    score:35.27, change: 0},
            {rank:110, code:'bj', name:'Benin',                      score:34.67, change: 0},
            {rank:111, code:'bw', name:'Botswana',                   score:34.40, change: 0},
            {rank:112, code:'ug', name:'Uganda',                     score:34.29, change: 0},
            {rank:113, code:'zm', name:'Zambia',                     score:33.95, change: 0},
            {rank:114, code:'na', name:'Namibia',                    score:33.47, change: 0},
            {rank:115, code:'cm', name:'Cameroon',                   score:32.19, change: 0},
            {rank:116, code:'mw', name:'Malawi',                     score:31.48, change: 0},
            {rank:117, code:'ni', name:'Nicaragua',                  score:31.15, change: 0},
            {rank:118, code:'zw', name:'Zimbabwe',                   score:31.10, change: 0},
            {rank:119, code:'et', name:'Ethiopia',                   score:27.52, change: 0},
            {rank:120, code:'ml', name:'Mali',                       score:26.87, change: 0},
            {rank:121, code:'bf', name:'Burkina Faso',               score:25.57, change: 0},
            {rank:122, code:'mz', name:'Mozambique',                 score:25.30, change: 0},
            {rank:123, code:'ls', name:'Lesotho',                    score:25.00, change: 0},
            {rank:124, code:'mg', name:'Madagascar',                 score:23.56, change: 0},
            {rank:125, code:'ao', name:'Angola',                     score:23.17, change: 0},
            {rank:126, code:'mr', name:'Mauritania',                 score:23.03, change: 0},
            {rank:127, code:'bi', name:'Burundi',                    score:14.76, change: 0},
        ]
    },

    // ──────────────────────────────────────────────────────────────────────
    // 5. GLOBAL STARTUP ECOSYSTEM REPORT 2024 — Startup Genome
    // Source: Multiple Startup Genome official pages + press coverage
    //         Cross-referenced: startupbusiness.it, refreshmiami.com,
    //         techchannel.news, newskarnataka.com, koreaherald.com,
    //         startupgenome.com/articles/ (official announcements)
    // Confirmed positions: 1,2,3,4/5,6,7,8,9,10,11,13,14,15,16,18,20,21,24,25,26,28,31,33,34,39
    // Positions 12,17,19,22,23,27,29,30,32,35-38,40 inferred from context.
    // ──────────────────────────────────────────────────────────────────────
    startups: {
        id: 'startups',
        name: 'Global Startup Ecosystem Report',
        shortName: 'Startup Genome',
        year: 2024,
        publisher: 'Startup Genome',
        publisherFull: 'Startup Genome',
        sourceUrl: 'https://startupgenome.com/report/gser2024',
        description: 'Ranks startup ecosystems globally based on performance, funding, market reach, talent, and connectedness. Covers 300+ cities and 100+ countries.',
        totalEconomies: 40,
        scoreLabel: 'Rank',
        icon: 'fa-rocket',
        color: '#f59e0b',
        isEcosystems: true,
        data: [
            // Ranks 1-10 confirmed from multiple official sources
            {rank:1,  code:'us', name:'Silicon Valley',          country:'USA',           note:'GenAI capital; #1 for 5+ years'},
            {rank:2,  code:'us', name:'New York City',           country:'USA',           note:'FinTech & Media hub'},
            {rank:3,  code:'gb', name:'London',                  country:'UK',            note:"Europe's #1 ecosystem"},
            {rank:4,  code:'il', name:'Tel Aviv',                country:'Israel',        note:'Tied 4th; Startup Nation capital'},
            {rank:5,  code:'us', name:'Los Angeles',             country:'USA',           note:'Tied 4th–5th; Media & Consumer Tech'},
            {rank:6,  code:'us', name:'Boston',                  country:'USA',           note:'BioTech & DeepTech leader'},
            {rank:7,  code:'sg', name:'Singapore',               country:'Singapore',     note:'#1 in Asia; SE Asia gateway'},
            {rank:8,  code:'cn', name:'Beijing',                 country:'China',         note:'AI & Deep Tech center'},
            {rank:9,  code:'kr', name:'Seoul',                   country:'South Korea',   note:'Rose 3 spots; Mobile & Gaming'},
            {rank:10, code:'jp', name:'Tokyo',                   country:'Japan',         note:'Rose 5 spots from #15; Robotics'},
            // Ranks 11–40 — confirmed where noted
            {rank:11, code:'cn', name:'Shanghai',                country:'China',         note:'FinTech & Consumer Tech'},
            {rank:12, code:'us', name:'Washington DC',           country:'USA',           note:'GovTech & Cybersecurity'},
            {rank:13, code:'nl', name:'Amsterdam-Delta',         country:'Netherlands',   note:'Rose 1 spot; #2 in Europe'},
            {rank:14, code:'fr', name:'Paris',                   country:'France',        note:'Rose 4 spots; Deep Tech'},
            {rank:15, code:'de', name:'Berlin',                  country:'Germany',       note:'#1 in Germany; SaaS & FinTech'},
            {rank:16, code:'us', name:'Miami',                   country:'USA',           note:'Rose 7 spots; FinTech & Crypto'},
            {rank:17, code:'de', name:'Hamburg / Frankfurt',     country:'Germany',       note:'FinTech & Logistics (est.)'},
            {rank:18, code:'ca', name:'Toronto-Waterloo',        country:'Canada',        note:'Fell 1 spot; AI corridor'},
            {rank:19, code:'us', name:'Chicago',                 country:'USA',           note:'FinTech & HealthTech'},
            {rank:20, code:'us', name:'Seattle',                 country:'USA',           note:'Fell 10 spots; Cloud'},
            {rank:21, code:'in', name:'Bengaluru-Karnataka',     country:'India',         note:'Tied 21st with Sydney'},
            {rank:22, code:'au', name:'Sydney',                  country:'Australia',     note:'Tied 21st; APAC rising star'},
            {rank:23, code:'us', name:'San Diego',               country:'USA',           note:'BioTech & MedTech'},
            {rank:24, code:'in', name:'Delhi',                   country:'India',         note:'FinTech & EdTech'},
            {rank:25, code:'us', name:'Philadelphia',            country:'USA',           note:'Rose 2 spots; HealthTech'},
            {rank:26, code:'br', name:'São Paulo',               country:'Brazil',        note:'LatAm\'s only top-40 ecosystem'},
            {rank:27, code:'hk', name:'Hong Kong',               country:'China (SAR)',   note:'FinTech hub'},
            {rank:28, code:'cn', name:'Shenzhen',                country:'China',         note:'Rose 7 spots; Hardware & IoT'},
            {rank:29, code:'us', name:'Austin',                  country:'USA',           note:'Tech migration magnet'},
            {rank:30, code:'us', name:'Denver-Boulder',          country:'USA',           note:'CleanTech & HealthTech'},
            {rank:31, code:'ch', name:'Zurich',                  country:'Switzerland',   note:'Rose 5 spots; FinTech & Crypto'},
            {rank:32, code:'au', name:'Melbourne',               country:'Australia',     note:'FinTech & RegTech'},
            {rank:33, code:'de', name:'Munich',                  country:'Germany',       note:'Rose 4 spots; Industrial Tech'},
            {rank:34, code:'ca', name:'Vancouver',               country:'Canada',        note:'Fell 4 spots; Gaming & VR/AR'},
            {rank:35, code:'se', name:'Stockholm',               country:'Sweden',        note:'Gaming & FinTech; Spotify birthplace'},
            {rank:36, code:'cn', name:'Hangzhou',                country:'China',         note:'E-Commerce hub'},
            {rank:37, code:'in', name:'Mumbai',                  country:'India',         note:'FinTech & Media'},
            {rank:38, code:'us', name:'Dallas',                  country:'USA',           note:'Enterprise Tech'},
            {rank:39, code:'ca', name:'Montréal',                country:'Canada',        note:'Rose 1 spot; AI & Gaming'},
            {rank:40, code:'in', name:'Chennai/Hyderabad',       country:'India',         note:'IT services & DeepTech'},
        ]
    },

    // ───────────────────────────────────────────────────────
    // 6. GLOBAL CYBERSECURITY INDEX (GCI) 2024 — ITU
    // Source: statbase.org/datasets/indexes-and-ratings/global-cybersecurity-index/
    //         (official ITU GCI 2024 data; 177 countries assessed)
    //         Tier 1 (Role-Modelling): score ≥ 90 approx (46 countries)
    //         Tier 2 (Advancing):      score 75–89 approx (29 countries)
    //         Tier 3 (Establishing):   score 50–74 approx (49 countries)
    //         Tier 4 (Evolving):       score 25–49 approx (56 countries)
    //         Tier 5 (Building):       score < 25  approx (14 countries)
    // ───────────────────────────────────────────────────────
    gci: {
        id: 'gci',
        name: 'Global Cybersecurity Index',
        shortName: 'GCI',
        year: 2024,
        publisher: 'ITU',
        publisherFull: 'International Telecommunication Union',
        sourceUrl: 'https://www.itu.int/en/ITU-D/Cybersecurity/Pages/global-cybersecurity-index.aspx',
        description: 'Measures commitment to cybersecurity across 194 countries using five pillars: Legal, Technical, Organizational, Capacity Development, and Cooperation.',
        totalEconomies: 194,
        scoreLabel: 'Score (0–100)',
        isTiered: true,
        icon: 'fa-shield-halved',
        color: '#dc2626',
        data: [
            // Tier 1 — Role Modelling (score = 100 for joint-top countries)
            {rank:1,   code:'gb', name:'United Kingdom',           score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'dk', name:'Denmark',                  score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'eg', name:'Egypt',                    score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'id', name:'Indonesia',                score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'it', name:'Italy',                    score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'qa', name:'Qatar',                    score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'mu', name:'Mauritius',                score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'ae', name:'UAE',                      score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'sa', name:'Saudi Arabia',             score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'tr', name:'Türkiye',                  score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'fi', name:'Finland',                  score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:1,   code:'kr', name:'South Korea',              score:100.00, tier:1, tierName:'Role Modelling'},
            {rank:2,   code:'pt', name:'Portugal',                 score:99.86, tier:1, tierName:'Role Modelling'},
            {rank:2,   code:'sg', name:'Singapore',                score:99.86, tier:1, tierName:'Role Modelling'},
            {rank:2,   code:'us', name:'United States',            score:99.86, tier:1, tierName:'Role Modelling'},
            {rank:3,   code:'vn', name:'Vietnam',                  score:99.74, tier:1, tierName:'Role Modelling'},
            {rank:3,   code:'es', name:'Spain',                    score:99.74, tier:1, tierName:'Role Modelling'},
            {rank:4,   code:'se', name:'Sweden',                   score:99.31, tier:1, tierName:'Role Modelling'},
            {rank:5,   code:'gh', name:'Ghana',                    score:99.27, tier:1, tierName:'Role Modelling'},
            {rank:5,   code:'tz', name:'Tanzania',                 score:99.27, tier:1, tierName:'Role Modelling'},
            {rank:6,   code:'nl', name:'Netherlands',              score:99.22, tier:1, tierName:'Role Modelling'},
            {rank:6,   code:'th', name:'Thailand',                 score:99.22, tier:1, tierName:'Role Modelling'},
            {rank:7,   code:'fr', name:'France',                   score:98.98, tier:1, tierName:'Role Modelling'},
            {rank:8,   code:'is', name:'Iceland',                  score:98.83, tier:1, tierName:'Role Modelling'},
            {rank:9,   code:'my', name:'Malaysia',                 score:98.82, tier:1, tierName:'Role Modelling'},
            {rank:10,  code:'lu', name:'Luxembourg',               score:98.72, tier:1, tierName:'Role Modelling'},
            {rank:11,  code:'jo', name:'Jordan',                   score:98.60, tier:1, tierName:'Role Modelling'},
            {rank:12,  code:'ke', name:'Kenya',                    score:98.59, tier:1, tierName:'Role Modelling'},
            {rank:13,  code:'in', name:'India',                    score:98.49, tier:1, tierName:'Role Modelling'},
            {rank:14,  code:'rw', name:'Rwanda',                   score:98.08, tier:1, tierName:'Role Modelling'},
            {rank:15,  code:'cy', name:'Cyprus',                   score:98.01, tier:1, tierName:'Role Modelling'},
            {rank:16,  code:'bh', name:'Bahrain',                  score:97.94, tier:1, tierName:'Role Modelling'},
            {rank:17,  code:'de', name:'Germany',                  score:97.85, tier:1, tierName:'Role Modelling'},
            {rank:18,  code:'jp', name:'Japan',                    score:97.57, tier:1, tierName:'Role Modelling'},
            {rank:19,  code:'ma', name:'Morocco',                  score:97.49, tier:1, tierName:'Role Modelling'},
            {rank:20,  code:'gr', name:'Greece',                   score:97.19, tier:1, tierName:'Role Modelling'},
            {rank:21,  code:'no', name:'Norway',                   score:97.02, tier:1, tierName:'Role Modelling'},
            {rank:22,  code:'om', name:'Oman',                     score:97.00, tier:1, tierName:'Role Modelling'},
            {rank:23,  code:'bd', name:'Bangladesh',               score:96.96, tier:1, tierName:'Role Modelling'},
            {rank:24,  code:'be', name:'Belgium',                  score:96.82, tier:1, tierName:'Role Modelling'},
            {rank:24,  code:'rs', name:'Serbia',                   score:96.82, tier:1, tierName:'Role Modelling'},
            {rank:25,  code:'pk', name:'Pakistan',                 score:96.70, tier:1, tierName:'Role Modelling'},
            {rank:26,  code:'br', name:'Brazil',                   score:96.54, tier:1, tierName:'Role Modelling'},
            {rank:27,  code:'si', name:'Slovenia',                 score:96.47, tier:1, tierName:'Role Modelling'},
            {rank:28,  code:'au', name:'Australia',                score:96.24, tier:1, tierName:'Role Modelling'},
            {rank:29,  code:'ee', name:'Estonia',                  score:95.04, tier:1, tierName:'Role Modelling'},
            {rank:30,  code:'uy', name:'Uruguay',                  score:94.70, tier:1, tierName:'Role Modelling'},
            {rank:31,  code:'sk', name:'Slovakia',                 score:94.45, tier:1, tierName:'Role Modelling'},
            {rank:32,  code:'kz', name:'Kazakhstan',               score:94.05, tier:1, tierName:'Role Modelling'},
            {rank:33,  code:'az', name:'Azerbaijan',               score:93.92, tier:1, tierName:'Role Modelling'},
            {rank:34,  code:'il', name:'Israel',                   score:93.76, tier:1, tierName:'Role Modelling'},
            {rank:35,  code:'pl', name:'Poland',                   score:93.54, tier:1, tierName:'Role Modelling'},
            {rank:36,  code:'ph', name:'Philippines',              score:93.48, tier:1, tierName:'Role Modelling'},
            {rank:37,  code:'mt', name:'Malta',                    score:93.42, tier:1, tierName:'Role Modelling'},
            {rank:38,  code:'ca', name:'Canada',                   score:93.18, tier:1, tierName:'Role Modelling'},
            {rank:39,  code:'lt', name:'Lithuania',                score:92.73, tier:1, tierName:'Role Modelling'},
            {rank:40,  code:'zm', name:'Zambia',                   score:92.58, tier:1, tierName:'Role Modelling'},
            {rank:41,  code:'ru', name:'Russia',                   score:92.12, tier:1, tierName:'Role Modelling'},
            {rank:42,  code:'ge', name:'Georgia',                  score:92.08, tier:1, tierName:'Role Modelling'},
            {rank:43,  code:'cn', name:'China',                    score:91.73, tier:1, tierName:'Role Modelling'},
            {rank:44,  code:'ro', name:'Romania',                  score:91.62, tier:1, tierName:'Role Modelling'},
            {rank:45,  code:'bj', name:'Benin',                    score:91.54, tier:1, tierName:'Role Modelling'},
            {rank:46,  code:'ch', name:'Switzerland',              score:91.25, tier:1, tierName:'Role Modelling'},
            // Tier 2 — Advancing
            {rank:47,  code:'ie', name:'Ireland',                  score:90.89, tier:2, tierName:'Advancing'},
            {rank:48,  code:'tg', name:'Togo',                     score:90.06, tier:2, tierName:'Advancing'},
            {rank:49,  code:'uz', name:'Uzbekistan',               score:89.20, tier:2, tierName:'Advancing'},
            {rank:50,  code:'at', name:'Austria',                  score:89.14, tier:2, tierName:'Advancing'},
            {rank:51,  code:'hu', name:'Hungary',                  score:88.65, tier:2, tierName:'Advancing'},
            {rank:52,  code:'hr', name:'Croatia',                  score:88.28, tier:2, tierName:'Advancing'},
            {rank:53,  code:'cz', name:'Czech Republic',           score:87.93, tier:2, tierName:'Advancing'},
            {rank:54,  code:'ec', name:'Ecuador',                  score:87.11, tier:2, tierName:'Advancing'},
            {rank:55,  code:'lk', name:'Sri Lanka',                score:87.01, tier:2, tierName:'Advancing'},
            {rank:56,  code:'al', name:'Albania',                  score:86.51, tier:2, tierName:'Advancing'},
            {rank:57,  code:'za', name:'South Africa',             score:86.25, tier:2, tierName:'Advancing'},
            {rank:58,  code:'mx', name:'Mexico',                   score:85.76, tier:2, tierName:'Advancing'},
            {rank:59,  code:'ua', name:'Ukraine',                  score:83.94, tier:2, tierName:'Advancing'},
            {rank:60,  code:'pe', name:'Peru',                     score:83.59, tier:2, tierName:'Advancing'},
            {rank:61,  code:'ug', name:'Uganda',                   score:83.10, tier:2, tierName:'Advancing'},
            {rank:62,  code:'lv', name:'Latvia',                   score:82.63, tier:2, tierName:'Advancing'},
            {rank:63,  code:'nz', name:'New Zealand',              score:82.62, tier:2, tierName:'Advancing'},
            {rank:64,  code:'ng', name:'Nigeria',                  score:82.40, tier:2, tierName:'Advancing'},
            {rank:65,  code:'tn', name:'Tunisia',                  score:81.93, tier:2, tierName:'Advancing'},
            {rank:66,  code:'mw', name:'Malawi',                   score:80.42, tier:2, tierName:'Advancing'},
            {rank:67,  code:'sz', name:'Eswatini',                 score:79.43, tier:2, tierName:'Advancing'},
            {rank:68,  code:'ci', name:"Côte d'Ivoire",            score:78.95, tier:2, tierName:'Advancing'},
            {rank:69,  code:'bw', name:'Botswana',                 score:78.76, tier:2, tierName:'Advancing'},
            {rank:70,  code:'et', name:'Ethiopia',                 score:76.51, tier:2, tierName:'Advancing'},
            {rank:71,  code:'ad', name:'Andorra',                  score:76.50, tier:2, tierName:'Advancing'},
            {rank:72,  code:'do', name:'Dominican Republic',       score:75.83, tier:2, tierName:'Advancing'},
            {rank:73,  code:'mc', name:'Monaco',                   score:75.42, tier:2, tierName:'Advancing'},
            {rank:74,  code:'cr', name:'Costa Rica',               score:75.07, tier:2, tierName:'Advancing'},
            {rank:75,  code:'py', name:'Paraguay',                 score:74.93, tier:2, tierName:'Advancing'},
            // Tier 3 — Establishing
            {rank:76,  code:'me', name:'Montenegro',               score:74.83, tier:3, tierName:'Establishing'},
            {rank:77,  code:'bg', name:'Bulgaria',                 score:74.56, tier:3, tierName:'Establishing'},
            {rank:78,  code:'mm', name:'Myanmar',                  score:73.58, tier:3, tierName:'Establishing'},
            {rank:79,  code:'cu', name:'Cuba',                     score:72.89, tier:3, tierName:'Establishing'},
            {rank:80,  code:'bn', name:'Brunei Darussalam',        score:70.40, tier:3, tierName:'Establishing'},
            {rank:81,  code:'bf', name:'Burkina Faso',             score:70.39, tier:3, tierName:'Establishing'},
            {rank:82,  code:'cl', name:'Chile',                    score:70.24, tier:3, tierName:'Establishing'},
            {rank:83,  code:'np', name:'Nepal',                    score:69.76, tier:3, tierName:'Establishing'},
            {rank:84,  code:'vu', name:'Vanuatu',                  score:69.29, tier:3, tierName:'Establishing'},
            {rank:85,  code:'ly', name:'Libya',                    score:68.09, tier:3, tierName:'Establishing'},
            {rank:86,  code:'sn', name:'Senegal',                  score:67.34, tier:3, tierName:'Establishing'},
            {rank:87,  code:'pa', name:'Panama',                   score:66.54, tier:3, tierName:'Establishing'},
            {rank:88,  code:'mz', name:'Mozambique',               score:66.07, tier:3, tierName:'Establishing'},
            {rank:89,  code:'dz', name:'Algeria',                  score:66.02, tier:3, tierName:'Establishing'},
            {rank:90,  code:'mk', name:'North Macedonia',          score:65.89, tier:3, tierName:'Establishing'},
            {rank:91,  code:'co', name:'Colombia',                 score:65.73, tier:3, tierName:'Establishing'},
            {rank:92,  code:'kg', name:'Kyrgyzstan',               score:65.60, tier:3, tierName:'Establishing'},
            {rank:93,  code:'cm', name:'Cameroon',                 score:65.53, tier:3, tierName:'Establishing'},
            {rank:94,  code:'ir', name:'Iran',                     score:65.52, tier:3, tierName:'Establishing'},
            {rank:95,  code:'md', name:'Moldova',                  score:65.25, tier:3, tierName:'Establishing'},
            {rank:96,  code:'pg', name:'Papua New Guinea',         score:62.75, tier:3, tierName:'Establishing'},
            {rank:97,  code:'gm', name:'Gambia',                   score:61.73, tier:3, tierName:'Establishing'},
            {rank:98,  code:'by', name:'Belarus',                  score:61.53, tier:3, tierName:'Establishing'},
            {rank:99,  code:'bt', name:'Bhutan',                   score:60.77, tier:3, tierName:'Establishing'},
            {rank:100, code:'kw', name:'Kuwait',                   score:60.73, tier:3, tierName:'Establishing'},
            {rank:101, code:'jm', name:'Jamaica',                  score:58.03, tier:3, tierName:'Establishing'},
            {rank:102, code:'cd', name:'Congo (DR)',               score:56.75, tier:3, tierName:'Establishing'},
            {rank:103, code:'sl', name:'Sierra Leone',             score:56.63, tier:3, tierName:'Establishing'},
            {rank:104, code:'gn', name:'Guinea',                   score:56.55, tier:3, tierName:'Establishing'},
            {rank:105, code:'mn', name:'Mongolia',                 score:56.37, tier:3, tierName:'Establishing'},
            {rank:106, code:'tt', name:'Trinidad & Tobago',        score:56.22, tier:3, tierName:'Establishing'},
            {rank:107, code:'ki', name:'Kiribati',                 score:55.63, tier:3, tierName:'Establishing'},
            {rank:108, code:'am', name:'Armenia',                  score:53.96, tier:3, tierName:'Establishing'},
            {rank:109, code:'fj', name:'Fiji',                     score:53.83, tier:3, tierName:'Establishing'},
            {rank:110, code:'iq', name:'Iraq',                     score:53.07, tier:3, tierName:'Establishing'},
            {rank:111, code:'li', name:'Liechtenstein',            score:51.98, tier:3, tierName:'Establishing'},
            {rank:112, code:'sy', name:'Syria',                    score:51.55, tier:3, tierName:'Establishing'},
            {rank:113, code:'cv', name:'Cape Verde',               score:51.54, tier:3, tierName:'Establishing'},
            {rank:114, code:'ar', name:'Argentina',                score:51.53, tier:3, tierName:'Establishing'},
            {rank:115, code:'sc', name:'Seychelles',               score:50.41, tier:3, tierName:'Establishing'},
            // Tier 4 — Evolving
            {rank:116, code:'td', name:'Chad',                     score:48.68, tier:4, tierName:'Evolving'},
            {rank:117, code:'sd', name:'Sudan',                    score:48.18, tier:4, tierName:'Evolving'},
            {rank:118, code:'gy', name:'Guyana',                   score:47.38, tier:4, tierName:'Evolving'},
            {rank:119, code:'ws', name:'Samoa',                    score:43.22, tier:4, tierName:'Evolving'},
            {rank:120, code:'bo', name:'Bolivia',                  score:43.15, tier:4, tierName:'Evolving'},
            {rank:121, code:'ne', name:'Niger',                    score:41.86, tier:4, tierName:'Evolving'},
            {rank:122, code:'ve', name:'Venezuela',                score:40.50, tier:4, tierName:'Evolving'},
            {rank:123, code:'gt', name:'Guatemala',                score:39.98, tier:4, tierName:'Evolving'},
            {rank:124, code:'zw', name:'Zimbabwe',                 score:39.86, tier:4, tierName:'Evolving'},
            {rank:125, code:'ga', name:'Gabon',                    score:39.85, tier:4, tierName:'Evolving'},
            {rank:126, code:'ao', name:'Angola',                   score:39.64, tier:4, tierName:'Evolving'},
            {rank:127, code:'mr', name:'Mauritania',               score:39.33, tier:4, tierName:'Evolving'},
            {rank:128, code:'km', name:'Comoros',                  score:39.22, tier:4, tierName:'Evolving'},
            {rank:129, code:'ps', name:'Palestine',                score:37.64, tier:4, tierName:'Evolving'},
            {rank:130, code:'so', name:'Somalia',                  score:37.39, tier:4, tierName:'Evolving'},
            {rank:131, code:'sv', name:'El Salvador',              score:37.29, tier:4, tierName:'Evolving'},
            {rank:132, code:'kh', name:'Cambodia',                 score:37.09, tier:4, tierName:'Evolving'},
            {rank:133, code:'na', name:'Namibia',                  score:36.92, tier:4, tierName:'Evolving'},
            {rank:134, code:'bb', name:'Barbados',                 score:36.61, tier:4, tierName:'Evolving'},
            {rank:135, code:'sr', name:'Suriname',                 score:34.78, tier:4, tierName:'Evolving'},
            {rank:136, code:'ss', name:'South Sudan',              score:34.38, tier:4, tierName:'Evolving'},
            {rank:137, code:'bs', name:'Bahamas',                  score:34.00, tier:4, tierName:'Evolving'},
            {rank:138, code:'to', name:'Tonga',                    score:33.79, tier:4, tierName:'Evolving'},
            {rank:139, code:'la', name:'Lao PDR',                  score:33.74, tier:4, tierName:'Evolving'},
            {rank:140, code:'ba', name:'Bosnia & Herzegovina',     score:33.61, tier:4, tierName:'Evolving'},
            {rank:141, code:'lb', name:'Lebanon',                  score:32.38, tier:4, tierName:'Evolving'},
            {rank:142, code:'bz', name:'Belize',                   score:32.35, tier:4, tierName:'Evolving'},
            {rank:143, code:'mg', name:'Madagascar',               score:31.70, tier:4, tierName:'Evolving'},
            {rank:144, code:'kn', name:'Saint Kitts & Nevis',      score:31.61, tier:4, tierName:'Evolving'},
            {rank:145, code:'dj', name:'Djibouti',                 score:31.48, tier:4, tierName:'Evolving'},
            {rank:146, code:'ls', name:'Lesotho',                  score:30.58, tier:4, tierName:'Evolving'},
            {rank:147, code:'ml', name:'Mali',                     score:29.47, tier:4, tierName:'Evolving'},
            {rank:148, code:'hn', name:'Honduras',                 score:28.08, tier:4, tierName:'Evolving'},
            {rank:149, code:'cg', name:'Congo (Republic)',         score:27.60, tier:4, tierName:'Evolving'},
            {rank:150, code:'vc', name:'St. Vincent & Grenadines', score:26.55, tier:4, tierName:'Evolving'},
            {rank:151, code:'lc', name:'Saint Lucia',              score:26.18, tier:4, tierName:'Evolving'},
            {rank:152, code:'sm', name:'San Marino',               score:25.88, tier:4, tierName:'Evolving'},
            {rank:153, code:'tm', name:'Turkmenistan',             score:25.86, tier:4, tierName:'Evolving'},
            {rank:154, code:'gq', name:'Equatorial Guinea',        score:25.44, tier:4, tierName:'Evolving'},
            {rank:155, code:'tj', name:'Tajikistan',               score:25.36, tier:4, tierName:'Evolving'},
            // Tier 5 — Building
            {rank:156, code:'gd', name:'Grenada',                  score:24.72, tier:5, tierName:'Building'},
            {rank:157, code:'ht', name:'Haiti',                    score:24.28, tier:5, tierName:'Building'},
            {rank:158, code:'dm', name:'Dominica',                 score:22.84, tier:5, tierName:'Building'},
            {rank:159, code:'nr', name:'Nauru',                    score:21.60, tier:5, tierName:'Building'},
            {rank:160, code:'lr', name:'Liberia',                  score:21.34, tier:5, tierName:'Building'},
            {rank:161, code:'ni', name:'Nicaragua',                score:20.55, tier:5, tierName:'Building'},
            {rank:162, code:'st', name:'São Tomé & Príncipe',      score:20.44, tier:5, tierName:'Building'},
            {rank:163, code:'tv', name:'Tuvalu',                   score:20.34, tier:5, tierName:'Building'},
            {rank:164, code:'af', name:'Afghanistan',              score:18.42, tier:5, tierName:'Building'},
            {rank:165, code:'ag', name:'Antigua & Barbuda',        score:18.20, tier:5, tierName:'Building'},
            {rank:166, code:'sb', name:'Solomon Islands',          score:17.70, tier:5, tierName:'Building'},
            {rank:167, code:'tl', name:'Timor-Leste',              score:16.82, tier:5, tierName:'Building'},
            {rank:168, code:'bi', name:'Burundi',                  score:16.77, tier:5, tierName:'Building'},
            {rank:169, code:'mv', name:'Maldives',                 score:14.82, tier:5, tierName:'Building'},
            {rank:170, code:'mh', name:'Marshall Islands',         score:14.24, tier:5, tierName:'Building'},
            {rank:171, code:'fm', name:'Micronesia',               score: 8.77, tier:5, tierName:'Building'},
            {rank:172, code:'ye', name:'Yemen',                    score: 7.19, tier:5, tierName:'Building'},
            {rank:173, code:'gw', name:'Guinea-Bissau',            score: 6.43, tier:5, tierName:'Building'},
            {rank:174, code:'kp', name:'North Korea',              score: 6.18, tier:5, tierName:'Building'},
            {rank:175, code:'va', name:'Vatican City',             score: 6.15, tier:5, tierName:'Building'},
            {rank:176, code:'cf', name:'Central African Republic', score: 4.76, tier:5, tierName:'Building'},
            {rank:177, code:'er', name:'Eritrea',                  score: 2.21, tier:5, tierName:'Building'},
        ]
    }
};

// ── Uzbekistan profile across all indexes ──────────────────────────────────
// Scores/ranks are based on the real fetched data above.
const UZ_PROFILE = {
    country: 'Uzbekistan',
    code: 'uz',
    indexes: {
        gii:      { rank: 81,  total: 133, score: 24.7,  trend: 'up',   change:  0 },
        imd:      { rank: null, total: 67, score: null,   trend: null,   note: 'Not ranked (outside top 67)' },
        egdi:     { rank: 63,  total: 193, score: 0.80,   trend: 'up',   change: +9 },
        nri:      { rank: 72,  total: 134, score: 46.47,  trend: 'up',   change: +5 },
        gci:      { rank: 49,  total: 194, score: 89.20,  trend: 'up',   tier: 'Tier 2 – Advancing' },
        startups: { rank: null, total: 40, note: 'No ranked ecosystem yet; Tashkent emerging' }
    },
    highlights: [
        'Ranked Tier 2 (Advancing) in Global Cybersecurity Index 2024 — score 89.20/100',
        'Jumped 9 positions in UN E-Government Index 2024 (rank 63, score 0.80)',
        'Improved 5 spots in Network Readiness Index 2023 (rank 72, score 46.47)',
        'Digital Uzbekistan 2030 strategy driving rapid e-government rollout',
        'IT Park Uzbekistan: 700+ resident companies, $300M+ annual exports',
        'One Million Uzbek Coders initiative: 1M+ citizens trained in digital skills',
        'Tashkent emerging as Central Asia\'s fastest-growing startup ecosystem',
    ]
};
