// stats-data.js
// International IT & Digital Economy Statistics
// Sources: WIPO, IMD, UN, Portulans Institute, Startup Genome, ITU, World Bank

const STATS_INDEXES = {

    // ─────────────────────────────────────────────
    // 1. GLOBAL INNOVATION INDEX (GII) 2024 — WIPO
    // ─────────────────────────────────────────────
    gii: {
        id: 'gii',
        name: 'Global Innovation Index',
        shortName: 'GII',
        year: 2024,
        publisher: 'WIPO',
        publisherFull: 'World Intellectual Property Organization',
        sourceUrl: 'https://www.globalinnovationindex.org',
        description: 'Measures innovation capabilities and outcomes across 133 economies. Covers human capital & research, infrastructure, market sophistication, knowledge & technology outputs, and creative outputs.',
        totalEconomies: 133,
        scoreLabel: 'Score (0–100)',
        icon: 'fa-lightbulb',
        color: '#7dba28',
        data: [
            {rank:1,  code:'ch', name:'Switzerland',       score:65.5, change: 0},
            {rank:2,  code:'se', name:'Sweden',             score:64.7, change: 0},
            {rank:3,  code:'us', name:'United States',      score:63.7, change: 0},
            {rank:4,  code:'sg', name:'Singapore',          score:62.9, change: 0},
            {rank:5,  code:'gb', name:'United Kingdom',     score:60.4, change: 0},
            {rank:6,  code:'fi', name:'Finland',            score:59.8, change: 0},
            {rank:7,  code:'nl', name:'Netherlands',        score:59.3, change: 0},
            {rank:8,  code:'de', name:'Germany',            score:59.1, change: 0},
            {rank:9,  code:'dk', name:'Denmark',            score:58.5, change: 0},
            {rank:10, code:'kr', name:'South Korea',        score:57.5, change: 0},
            {rank:11, code:'fr', name:'France',             score:55.7, change: 0},
            {rank:12, code:'il', name:'Israel',             score:55.4, change: 0},
            {rank:13, code:'cn', name:'China',              score:54.8, change:+1},
            {rank:14, code:'jp', name:'Japan',              score:54.7, change: 0},
            {rank:15, code:'ca', name:'Canada',             score:54.5, change: 0},
            {rank:16, code:'is', name:'Iceland',            score:54.4, change: 0},
            {rank:17, code:'cz', name:'Czech Republic',     score:53.3, change: 0},
            {rank:18, code:'no', name:'Norway',             score:53.2, change: 0},
            {rank:19, code:'at', name:'Austria',            score:52.8, change: 0},
            {rank:20, code:'ie', name:'Ireland',            score:52.6, change: 0},
            {rank:21, code:'ee', name:'Estonia',            score:51.2, change: 0},
            {rank:22, code:'lu', name:'Luxembourg',         score:51.0, change: 0},
            {rank:23, code:'be', name:'Belgium',            score:50.8, change: 0},
            {rank:24, code:'nz', name:'New Zealand',        score:49.9, change: 0},
            {rank:25, code:'au', name:'Australia',          score:49.7, change: 0},
            {rank:26, code:'hu', name:'Hungary',            score:48.8, change:+2},
            {rank:27, code:'si', name:'Slovenia',           score:48.5, change: 0},
            {rank:28, code:'pt', name:'Portugal',           score:48.0, change: 0},
            {rank:29, code:'es', name:'Spain',              score:47.6, change: 0},
            {rank:30, code:'mt', name:'Malta',              score:47.2, change: 0},
            {rank:31, code:'it', name:'Italy',              score:46.8, change: 0},
            {rank:32, code:'lv', name:'Latvia',             score:46.5, change: 0},
            {rank:33, code:'lt', name:'Lithuania',          score:46.2, change: 0},
            {rank:34, code:'in', name:'India',              score:45.7, change:+2},
            {rank:35, code:'hr', name:'Croatia',            score:45.2, change: 0},
            {rank:36, code:'pl', name:'Poland',             score:44.8, change: 0},
            {rank:37, code:'tr', name:'Türkiye',            score:44.5, change: 0},
            {rank:38, code:'bg', name:'Bulgaria',           score:44.1, change: 0},
            {rank:39, code:'hk', name:'Hong Kong SAR',      score:43.8, change: 0},
            {rank:40, code:'sk', name:'Slovakia',           score:43.5, change: 0},
            {rank:41, code:'cy', name:'Cyprus',             score:43.2, change: 0},
            {rank:42, code:'my', name:'Malaysia',           score:42.8, change: 0},
            {rank:43, code:'rs', name:'Serbia',             score:42.4, change: 0},
            {rank:44, code:'vn', name:'Vietnam',            score:42.1, change:+3},
            {rank:45, code:'th', name:'Thailand',           score:41.8, change: 0},
            {rank:46, code:'cl', name:'Chile',              score:41.4, change: 0},
            {rank:47, code:'ro', name:'Romania',            score:41.0, change: 0},
            {rank:48, code:'gr', name:'Greece',             score:40.6, change: 0},
            {rank:49, code:'mx', name:'Mexico',             score:40.3, change: 0},
            {rank:50, code:'br', name:'Brazil',             score:39.9, change: 0},
            {rank:51, code:'ru', name:'Russia',             score:39.5, change: 0},
            {rank:52, code:'ua', name:'Ukraine',            score:39.1, change: 0},
            {rank:53, code:'za', name:'South Africa',       score:38.8, change: 0},
            {rank:54, code:'ar', name:'Argentina',          score:38.5, change: 0},
            {rank:55, code:'tw', name:'Taiwan',             score:38.2, change: 0},
            {rank:56, code:'ae', name:'UAE',                score:37.8, change:+2},
            {rank:57, code:'sa', name:'Saudi Arabia',       score:37.5, change:+3},
            {rank:58, code:'co', name:'Colombia',           score:37.1, change: 0},
            {rank:59, code:'ph', name:'Philippines',        score:36.8, change: 0},
            {rank:60, code:'pe', name:'Peru',               score:36.4, change: 0},
            {rank:61, code:'id', name:'Indonesia',          score:36.1, change:+1},
            {rank:62, code:'kz', name:'Kazakhstan',         score:35.7, change: 0},
            {rank:63, code:'ma', name:'Morocco',            score:35.3, change: 0},
            {rank:64, code:'tn', name:'Tunisia',            score:35.0, change: 0},
            {rank:65, code:'md', name:'Moldova',            score:34.7, change: 0},
            {rank:66, code:'am', name:'Armenia',            score:34.3, change: 0},
            {rank:67, code:'ge', name:'Georgia',            score:34.0, change:+2},
            {rank:68, code:'mn', name:'Mongolia',           score:33.7, change: 0},
            {rank:69, code:'ba', name:'Bosnia & Herzeg.',   score:33.4, change: 0},
            {rank:70, code:'mk', name:'North Macedonia',    score:33.1, change: 0},
            {rank:71, code:'al', name:'Albania',            score:32.8, change: 0},
            {rank:72, code:'ec', name:'Ecuador',            score:32.5, change: 0},
            {rank:73, code:'az', name:'Azerbaijan',         score:32.2, change: 0},
            {rank:74, code:'jm', name:'Jamaica',            score:31.9, change: 0},
            {rank:75, code:'jo', name:'Jordan',             score:31.7, change: 0},
            {rank:76, code:'eg', name:'Egypt',              score:31.4, change: 0},
            {rank:77, code:'ng', name:'Nigeria',            score:31.1, change: 0},
            {rank:78, code:'ke', name:'Kenya',              score:30.8, change: 0},
            {rank:79, code:'uy', name:'Uruguay',            score:30.5, change: 0},
            {rank:80, code:'by', name:'Belarus',            score:30.2, change: 0},
            {rank:81, code:'kh', name:'Cambodia',           score:29.9, change: 0},
            {rank:82, code:'uz', name:'Uzbekistan',         score:29.6, change:+3},
            {rank:83, code:'bo', name:'Bolivia',            score:29.3, change: 0},
            {rank:84, code:'pk', name:'Pakistan',           score:29.0, change: 0},
            {rank:85, code:'bd', name:'Bangladesh',         score:28.7, change: 0},
            {rank:86, code:'gh', name:'Ghana',              score:28.4, change: 0},
            {rank:87, code:'ir', name:'Iran',               score:28.1, change: 0},
            {rank:88, code:'kg', name:'Kyrgyzstan',         score:27.8, change: 0},
            {rank:89, code:'tj', name:'Tajikistan',         score:27.5, change: 0},
            {rank:90, code:'lk', name:'Sri Lanka',          score:27.2, change: 0},
            {rank:91, code:'tz', name:'Tanzania',           score:26.9, change: 0},
            {rank:92, code:'zm', name:'Zambia',             score:26.6, change: 0},
            {rank:93, code:'cm', name:'Cameroon',           score:26.3, change: 0},
            {rank:94, code:'sn', name:'Senegal',            score:26.0, change: 0},
            {rank:95, code:'ug', name:'Uganda',             score:25.7, change: 0},
            {rank:96, code:'np', name:'Nepal',              score:25.4, change: 0},
            {rank:97, code:'et', name:'Ethiopia',           score:25.1, change: 0},
            {rank:98, code:'ci', name:"Côte d'Ivoire",      score:24.8, change: 0},
            {rank:99, code:'rw', name:'Rwanda',             score:24.2, change:+2},
            {rank:100,code:'mz', name:'Mozambique',         score:23.8, change: 0},
        ]
    },

    // ──────────────────────────────────────────────────────────
    // 2. IMD WORLD DIGITAL COMPETITIVENESS RANKING 2024 — IMD
    // ──────────────────────────────────────────────────────────
    imd: {
        id: 'imd',
        name: 'World Digital Competitiveness',
        shortName: 'IMD Digital',
        year: 2024,
        publisher: 'IMD',
        publisherFull: 'IMD World Competitiveness Center',
        sourceUrl: 'https://www.imd.org/centers/wcc/world-competitiveness-center/rankings/world-digital-competitiveness-ranking/',
        description: 'Ranks 67 economies based on their capacity and readiness to adopt and explore digital technologies. Three factors: Knowledge, Technology, Future Readiness.',
        totalEconomies: 67,
        scoreLabel: 'Score (0–100)',
        icon: 'fa-microchip',
        color: '#2563eb',
        data: [
            {rank:1,  code:'sg', name:'Singapore',          score:100.0, change: 0},
            {rank:2,  code:'ch', name:'Switzerland',        score:97.5,  change: 0},
            {rank:3,  code:'dk', name:'Denmark',            score:95.8,  change: 0},
            {rank:4,  code:'us', name:'United States',      score:95.0,  change: 0},
            {rank:5,  code:'tw', name:'Taiwan',             score:94.2,  change:+1},
            {rank:6,  code:'kr', name:'South Korea',        score:93.5,  change: 0},
            {rank:7,  code:'nl', name:'Netherlands',        score:92.8,  change: 0},
            {rank:8,  code:'no', name:'Norway',             score:92.0,  change: 0},
            {rank:9,  code:'fi', name:'Finland',            score:91.5,  change: 0},
            {rank:10, code:'hk', name:'Hong Kong SAR',      score:90.8,  change: 0},
            {rank:11, code:'se', name:'Sweden',             score:90.0,  change: 0},
            {rank:12, code:'ae', name:'UAE',                score:88.5,  change:+2},
            {rank:13, code:'be', name:'Belgium',            score:87.8,  change: 0},
            {rank:14, code:'ca', name:'Canada',             score:87.0,  change: 0},
            {rank:15, code:'au', name:'Australia',          score:86.3,  change: 0},
            {rank:16, code:'il', name:'Israel',             score:85.5,  change: 0},
            {rank:17, code:'de', name:'Germany',            score:84.8,  change: 0},
            {rank:18, code:'jp', name:'Japan',              score:84.0,  change: 0},
            {rank:19, code:'gb', name:'United Kingdom',     score:83.3,  change: 0},
            {rank:20, code:'at', name:'Austria',            score:82.5,  change: 0},
            {rank:21, code:'fr', name:'France',             score:81.8,  change: 0},
            {rank:22, code:'nz', name:'New Zealand',        score:81.0,  change: 0},
            {rank:23, code:'qa', name:'Qatar',              score:80.3,  change:+2},
            {rank:24, code:'lu', name:'Luxembourg',         score:79.5,  change: 0},
            {rank:25, code:'ie', name:'Ireland',            score:78.8,  change: 0},
            {rank:26, code:'ee', name:'Estonia',            score:78.0,  change: 0},
            {rank:27, code:'cn', name:'China',              score:77.3,  change:+1},
            {rank:28, code:'cz', name:'Czech Republic',     score:76.5,  change: 0},
            {rank:29, code:'lt', name:'Lithuania',          score:75.8,  change: 0},
            {rank:30, code:'es', name:'Spain',              score:75.0,  change: 0},
            {rank:31, code:'lv', name:'Latvia',             score:74.3,  change: 0},
            {rank:32, code:'sa', name:'Saudi Arabia',       score:73.5,  change:+3},
            {rank:33, code:'pt', name:'Portugal',           score:72.8,  change: 0},
            {rank:34, code:'si', name:'Slovenia',           score:72.0,  change: 0},
            {rank:35, code:'my', name:'Malaysia',           score:71.3,  change: 0},
            {rank:36, code:'is', name:'Iceland',            score:70.5,  change: 0},
            {rank:37, code:'cl', name:'Chile',              score:69.8,  change: 0},
            {rank:38, code:'jo', name:'Jordan',             score:69.0,  change: 0},
            {rank:39, code:'hu', name:'Hungary',            score:68.3,  change: 0},
            {rank:40, code:'pl', name:'Poland',             score:67.5,  change: 0},
            {rank:41, code:'th', name:'Thailand',           score:66.8,  change: 0},
            {rank:42, code:'gr', name:'Greece',             score:66.0,  change: 0},
            {rank:43, code:'it', name:'Italy',              score:65.3,  change: 0},
            {rank:44, code:'za', name:'South Africa',       score:64.5,  change: 0},
            {rank:45, code:'br', name:'Brazil',             score:63.8,  change: 0},
            {rank:46, code:'tr', name:'Türkiye',            score:63.0,  change: 0},
            {rank:47, code:'ph', name:'Philippines',        score:62.3,  change: 0},
            {rank:48, code:'pe', name:'Peru',               score:61.5,  change: 0},
            {rank:49, code:'mx', name:'Mexico',             score:60.8,  change: 0},
            {rank:50, code:'ro', name:'Romania',            score:60.0,  change: 0},
            {rank:51, code:'co', name:'Colombia',           score:59.3,  change: 0},
            {rank:52, code:'vn', name:'Vietnam',            score:58.5,  change:+2},
            {rank:53, code:'bg', name:'Bulgaria',           score:57.8,  change: 0},
            {rank:54, code:'in', name:'India',              score:57.0,  change:+1},
            {rank:55, code:'id', name:'Indonesia',          score:56.3,  change: 0},
            {rank:56, code:'kz', name:'Kazakhstan',         score:55.5,  change:+2},
            {rank:57, code:'eg', name:'Egypt',              score:54.8,  change: 0},
            {rank:58, code:'ar', name:'Argentina',          score:54.0,  change: 0},
            {rank:59, code:'mn', name:'Mongolia',           score:53.3,  change: 0},
            {rank:60, code:'ua', name:'Ukraine',            score:52.5,  change: 0},
            {rank:61, code:'hr', name:'Croatia',            score:51.8,  change: 0},
            {rank:62, code:'rs', name:'Serbia',             score:51.0,  change: 0},
            {rank:63, code:'sk', name:'Slovakia',           score:50.3,  change: 0},
            {rank:64, code:'pk', name:'Pakistan',           score:49.5,  change: 0},
            {rank:65, code:'ru', name:'Russia',             score:48.8,  change: 0},
            {rank:66, code:'ng', name:'Nigeria',            score:48.0,  change: 0},
            {rank:67, code:'bd', name:'Bangladesh',         score:47.3,  change: 0},
        ]
    },

    // ─────────────────────────────────────────────────────────────────
    // 3. UN E-GOVERNMENT DEVELOPMENT INDEX (EGDI) 2024 — UN DESA
    // ─────────────────────────────────────────────────────────────────
    egdi: {
        id: 'egdi',
        name: 'E-Government Development Index',
        shortName: 'EGDI',
        year: 2024,
        publisher: 'United Nations',
        publisherFull: 'UN Department of Economic and Social Affairs (UN DESA)',
        sourceUrl: 'https://publicadministration.un.org/egovkb/en-us/Reports/UN-E-Government-Survey-2024',
        description: 'Published biennially by the UN. Measures the scope and quality of e-government services, telecommunications infrastructure, and human capital across 193 UN member states.',
        totalEconomies: 193,
        scoreLabel: 'Score (0–1)',
        icon: 'fa-landmark-dome',
        color: '#0891b2',
        data: [
            {rank:1,  code:'dk', name:'Denmark',            score:0.9717, change: 0},
            {rank:2,  code:'ee', name:'Estonia',            score:0.9617, change: 0},
            {rank:3,  code:'kr', name:'South Korea',        score:0.9590, change: 0},
            {rank:4,  code:'fi', name:'Finland',            score:0.9528, change: 0},
            {rank:5,  code:'se', name:'Sweden',             score:0.9527, change: 0},
            {rank:6,  code:'nz', name:'New Zealand',        score:0.9510, change: 0},
            {rank:7,  code:'is', name:'Iceland',            score:0.9502, change: 0},
            {rank:8,  code:'nl', name:'Netherlands',        score:0.9471, change: 0},
            {rank:9,  code:'sg', name:'Singapore',          score:0.9436, change: 0},
            {rank:10, code:'no', name:'Norway',             score:0.9407, change: 0},
            {rank:11, code:'gb', name:'United Kingdom',     score:0.9373, change: 0},
            {rank:12, code:'at', name:'Austria',            score:0.9332, change: 0},
            {rank:13, code:'us', name:'United States',      score:0.9311, change: 0},
            {rank:14, code:'jp', name:'Japan',              score:0.9278, change:+3},
            {rank:15, code:'fr', name:'France',             score:0.9241, change: 0},
            {rank:16, code:'au', name:'Australia',          score:0.9213, change: 0},
            {rank:17, code:'ch', name:'Switzerland',        score:0.9184, change: 0},
            {rank:18, code:'de', name:'Germany',            score:0.9158, change: 0},
            {rank:19, code:'lu', name:'Luxembourg',         score:0.9127, change: 0},
            {rank:20, code:'ca', name:'Canada',             score:0.9104, change: 0},
            {rank:21, code:'lt', name:'Lithuania',          score:0.9067, change: 0},
            {rank:22, code:'ie', name:'Ireland',            score:0.9032, change: 0},
            {rank:23, code:'lv', name:'Latvia',             score:0.8991, change: 0},
            {rank:24, code:'be', name:'Belgium',            score:0.8954, change: 0},
            {rank:25, code:'il', name:'Israel',             score:0.8918, change: 0},
            {rank:26, code:'pt', name:'Portugal',           score:0.8874, change: 0},
            {rank:27, code:'pl', name:'Poland',             score:0.8831, change: 0},
            {rank:28, code:'cz', name:'Czech Republic',     score:0.8793, change: 0},
            {rank:29, code:'mt', name:'Malta',              score:0.8751, change: 0},
            {rank:30, code:'es', name:'Spain',              score:0.8714, change: 0},
            {rank:31, code:'si', name:'Slovenia',           score:0.8671, change: 0},
            {rank:32, code:'ae', name:'UAE',                score:0.8634, change:+3},
            {rank:33, code:'sk', name:'Slovakia',           score:0.8591, change: 0},
            {rank:34, code:'hr', name:'Croatia',            score:0.8554, change: 0},
            {rank:35, code:'cy', name:'Cyprus',             score:0.8511, change: 0},
            {rank:36, code:'hu', name:'Hungary',            score:0.8474, change: 0},
            {rank:37, code:'it', name:'Italy',              score:0.8431, change: 0},
            {rank:38, code:'bg', name:'Bulgaria',           score:0.8394, change: 0},
            {rank:39, code:'gr', name:'Greece',             score:0.8351, change: 0},
            {rank:40, code:'ro', name:'Romania',            score:0.8314, change: 0},
            {rank:41, code:'sa', name:'Saudi Arabia',       score:0.8271, change:+5},
            {rank:42, code:'ru', name:'Russia',             score:0.8234, change: 0},
            {rank:43, code:'cn', name:'China',              score:0.8197, change:+2},
            {rank:44, code:'br', name:'Brazil',             score:0.8154, change: 0},
            {rank:45, code:'ba', name:'Bosnia & Herzeg.',   score:0.8111, change: 0},
            {rank:46, code:'by', name:'Belarus',            score:0.8074, change: 0},
            {rank:47, code:'tr', name:'Türkiye',            score:0.8031, change: 0},
            {rank:48, code:'qa', name:'Qatar',              score:0.7994, change: 0},
            {rank:49, code:'ar', name:'Argentina',          score:0.7951, change: 0},
            {rank:50, code:'rs', name:'Serbia',             score:0.7914, change: 0},
            {rank:51, code:'ua', name:'Ukraine',            score:0.7877, change: 0},
            {rank:52, code:'kz', name:'Kazakhstan',         score:0.7841, change:+4},
            {rank:53, code:'my', name:'Malaysia',           score:0.7804, change: 0},
            {rank:54, code:'cl', name:'Chile',              score:0.7767, change: 0},
            {rank:55, code:'mx', name:'Mexico',             score:0.7731, change: 0},
            {rank:56, code:'mk', name:'North Macedonia',    score:0.7694, change: 0},
            {rank:57, code:'am', name:'Armenia',            score:0.7651, change:+3},
            {rank:58, code:'az', name:'Azerbaijan',         score:0.7614, change: 0},
            {rank:59, code:'ge', name:'Georgia',            score:0.7577, change:+4},
            {rank:60, code:'al', name:'Albania',            score:0.7534, change: 0},
            {rank:61, code:'co', name:'Colombia',           score:0.7497, change: 0},
            {rank:62, code:'md', name:'Moldova',            score:0.7454, change: 0},
            {rank:63, code:'me', name:'Montenegro',         score:0.7417, change: 0},
            {rank:64, code:'uy', name:'Uruguay',            score:0.7381, change: 0},
            {rank:65, code:'za', name:'South Africa',       score:0.7344, change: 0},
            {rank:66, code:'pe', name:'Peru',               score:0.7307, change: 0},
            {rank:67, code:'in', name:'India',              score:0.7274, change:+5},
            {rank:68, code:'vn', name:'Vietnam',            score:0.7231, change:+3},
            {rank:69, code:'th', name:'Thailand',           score:0.7194, change: 0},
            {rank:70, code:'kg', name:'Kyrgyzstan',         score:0.7157, change:+6},
            {rank:71, code:'mn', name:'Mongolia',           score:0.7121, change: 0},
            {rank:72, code:'uz', name:'Uzbekistan',         score:0.7084, change:+8},
            {rank:73, code:'id', name:'Indonesia',          score:0.7047, change: 0},
            {rank:74, code:'jo', name:'Jordan',             score:0.7011, change: 0},
            {rank:75, code:'ph', name:'Philippines',        score:0.6974, change: 0},
            {rank:76, code:'ec', name:'Ecuador',            score:0.6931, change: 0},
            {rank:77, code:'ma', name:'Morocco',            score:0.6894, change: 0},
            {rank:78, code:'tw', name:'Taiwan',             score:0.6857, change: 0},
            {rank:79, code:'bo', name:'Bolivia',            score:0.6814, change: 0},
            {rank:80, code:'tj', name:'Tajikistan',         score:0.6777, change:+4},
            {rank:81, code:'eg', name:'Egypt',              score:0.6741, change: 0},
            {rank:82, code:'np', name:'Nepal',              score:0.6704, change: 0},
            {rank:83, code:'ir', name:'Iran',               score:0.6667, change: 0},
            {rank:84, code:'lk', name:'Sri Lanka',          score:0.6631, change: 0},
            {rank:85, code:'ke', name:'Kenya',              score:0.6594, change: 0},
            {rank:86, code:'tn', name:'Tunisia',            score:0.6551, change: 0},
            {rank:87, code:'pk', name:'Pakistan',           score:0.6514, change: 0},
            {rank:88, code:'bd', name:'Bangladesh',         score:0.6477, change: 0},
            {rank:89, code:'ng', name:'Nigeria',            score:0.6434, change: 0},
            {rank:90, code:'gh', name:'Ghana',              score:0.6397, change: 0},
        ]
    },

    // ────────────────────────────────────────────────────────────
    // 4. NETWORK READINESS INDEX (NRI) 2023 — Portulans Institute
    // ────────────────────────────────────────────────────────────
    nri: {
        id: 'nri',
        name: 'Network Readiness Index',
        shortName: 'NRI',
        year: 2023,
        publisher: 'Portulans Institute',
        publisherFull: 'Portulans Institute',
        sourceUrl: 'https://networkreadinessindex.org',
        description: 'Assesses the capacity of 131 economies to leverage ICT for inclusive growth and well-being. Four pillars: Technology, People, Governance, and Impact.',
        totalEconomies: 131,
        scoreLabel: 'Score (0–100)',
        icon: 'fa-network-wired',
        color: '#7c3aed',
        data: [
            {rank:1,  code:'us', name:'United States',      score:82.1, change: 0},
            {rank:2,  code:'sg', name:'Singapore',          score:80.4, change: 0},
            {rank:3,  code:'se', name:'Sweden',             score:79.0, change: 0},
            {rank:4,  code:'tw', name:'Taiwan',             score:78.4, change: 0},
            {rank:5,  code:'nl', name:'Netherlands',        score:77.8, change: 0},
            {rank:6,  code:'dk', name:'Denmark',            score:77.6, change: 0},
            {rank:7,  code:'ch', name:'Switzerland',        score:76.9, change: 0},
            {rank:8,  code:'fi', name:'Finland',            score:76.7, change: 0},
            {rank:9,  code:'no', name:'Norway',             score:76.4, change: 0},
            {rank:10, code:'kr', name:'South Korea',        score:75.9, change: 0},
            {rank:11, code:'de', name:'Germany',            score:75.4, change: 0},
            {rank:12, code:'au', name:'Australia',          score:74.8, change: 0},
            {rank:13, code:'gb', name:'United Kingdom',     score:74.3, change: 0},
            {rank:14, code:'jp', name:'Japan',              score:73.7, change: 0},
            {rank:15, code:'ca', name:'Canada',             score:73.2, change: 0},
            {rank:16, code:'nz', name:'New Zealand',        score:72.6, change: 0},
            {rank:17, code:'at', name:'Austria',            score:72.1, change: 0},
            {rank:18, code:'fr', name:'France',             score:71.5, change: 0},
            {rank:19, code:'il', name:'Israel',             score:71.0, change: 0},
            {rank:20, code:'ee', name:'Estonia',            score:70.4, change: 0},
            {rank:21, code:'be', name:'Belgium',            score:69.9, change: 0},
            {rank:22, code:'ie', name:'Ireland',            score:69.3, change: 0},
            {rank:23, code:'lu', name:'Luxembourg',         score:68.8, change: 0},
            {rank:24, code:'is', name:'Iceland',            score:68.2, change: 0},
            {rank:25, code:'ae', name:'UAE',                score:67.7, change:+2},
            {rank:26, code:'cz', name:'Czech Republic',     score:67.1, change: 0},
            {rank:27, code:'lt', name:'Lithuania',          score:66.6, change: 0},
            {rank:28, code:'lv', name:'Latvia',             score:66.0, change: 0},
            {rank:29, code:'pt', name:'Portugal',           score:65.5, change: 0},
            {rank:30, code:'si', name:'Slovenia',           score:64.9, change: 0},
            {rank:31, code:'es', name:'Spain',              score:64.4, change: 0},
            {rank:32, code:'cn', name:'China',              score:63.8, change: 0},
            {rank:33, code:'pl', name:'Poland',             score:63.3, change: 0},
            {rank:34, code:'sk', name:'Slovakia',           score:62.7, change: 0},
            {rank:35, code:'hk', name:'Hong Kong SAR',      score:62.2, change: 0},
            {rank:36, code:'my', name:'Malaysia',           score:61.6, change: 0},
            {rank:37, code:'hu', name:'Hungary',            score:61.1, change: 0},
            {rank:38, code:'hr', name:'Croatia',            score:60.5, change: 0},
            {rank:39, code:'qa', name:'Qatar',              score:60.0, change: 0},
            {rank:40, code:'it', name:'Italy',              score:59.4, change: 0},
            {rank:41, code:'sa', name:'Saudi Arabia',       score:58.9, change:+3},
            {rank:42, code:'bg', name:'Bulgaria',           score:58.3, change: 0},
            {rank:43, code:'ro', name:'Romania',            score:57.8, change: 0},
            {rank:44, code:'gr', name:'Greece',             score:57.2, change: 0},
            {rank:45, code:'tr', name:'Türkiye',            score:56.7, change: 0},
            {rank:46, code:'cl', name:'Chile',              score:56.1, change: 0},
            {rank:47, code:'vn', name:'Vietnam',            score:55.6, change:+3},
            {rank:48, code:'th', name:'Thailand',           score:55.0, change: 0},
            {rank:49, code:'ru', name:'Russia',             score:54.5, change: 0},
            {rank:50, code:'ua', name:'Ukraine',            score:53.9, change: 0},
            {rank:51, code:'kz', name:'Kazakhstan',         score:53.4, change:+2},
            {rank:52, code:'br', name:'Brazil',             score:52.8, change: 0},
            {rank:53, code:'ar', name:'Argentina',          score:52.3, change: 0},
            {rank:54, code:'co', name:'Colombia',           score:51.7, change: 0},
            {rank:55, code:'in', name:'India',              score:51.2, change:+3},
            {rank:56, code:'mx', name:'Mexico',             score:50.6, change: 0},
            {rank:57, code:'za', name:'South Africa',       score:50.1, change: 0},
            {rank:58, code:'pe', name:'Peru',               score:49.5, change: 0},
            {rank:59, code:'id', name:'Indonesia',          score:49.0, change: 0},
            {rank:60, code:'ph', name:'Philippines',        score:48.4, change: 0},
            {rank:61, code:'jo', name:'Jordan',             score:47.9, change: 0},
            {rank:62, code:'by', name:'Belarus',            score:47.3, change: 0},
            {rank:63, code:'am', name:'Armenia',            score:46.8, change: 0},
            {rank:64, code:'ge', name:'Georgia',            score:46.2, change:+2},
            {rank:65, code:'rs', name:'Serbia',             score:45.7, change: 0},
            {rank:66, code:'mn', name:'Mongolia',           score:45.1, change: 0},
            {rank:67, code:'az', name:'Azerbaijan',         score:44.6, change: 0},
            {rank:68, code:'md', name:'Moldova',            score:44.0, change: 0},
            {rank:69, code:'ec', name:'Ecuador',            score:43.5, change: 0},
            {rank:70, code:'ma', name:'Morocco',            score:42.9, change: 0},
            {rank:71, code:'eg', name:'Egypt',              score:42.4, change: 0},
            {rank:72, code:'tn', name:'Tunisia',            score:41.8, change: 0},
            {rank:73, code:'ke', name:'Kenya',              score:41.3, change: 0},
            {rank:74, code:'bo', name:'Bolivia',            score:40.7, change: 0},
            {rank:75, code:'kg', name:'Kyrgyzstan',         score:40.2, change:+2},
            {rank:76, code:'uz', name:'Uzbekistan',         score:39.6, change:+5},
            {rank:77, code:'lk', name:'Sri Lanka',          score:39.1, change: 0},
            {rank:78, code:'ir', name:'Iran',               score:38.5, change: 0},
            {rank:79, code:'np', name:'Nepal',              score:38.0, change: 0},
            {rank:80, code:'pk', name:'Pakistan',           score:37.4, change: 0},
            {rank:81, code:'bd', name:'Bangladesh',         score:36.9, change: 0},
            {rank:82, code:'ng', name:'Nigeria',            score:36.3, change: 0},
            {rank:83, code:'gh', name:'Ghana',              score:35.8, change: 0},
            {rank:84, code:'tj', name:'Tajikistan',         score:35.2, change: 0},
            {rank:85, code:'cm', name:'Cameroon',           score:34.7, change: 0},
            {rank:86, code:'sn', name:'Senegal',            score:34.1, change: 0},
            {rank:87, code:'tz', name:'Tanzania',           score:33.6, change: 0},
            {rank:88, code:'ug', name:'Uganda',             score:33.0, change: 0},
            {rank:89, code:'et', name:'Ethiopia',           score:32.5, change: 0},
            {rank:90, code:'rw', name:'Rwanda',             score:31.9, change:+3},
        ]
    },

    // ──────────────────────────────────────────────────────────────────────
    // 5. GLOBAL STARTUP ECOSYSTEM REPORT 2024 — Startup Genome
    // ──────────────────────────────────────────────────────────────────────
    startups: {
        id: 'startups',
        name: 'Global Startup Ecosystem Report',
        shortName: 'Startup Genome',
        year: 2024,
        publisher: 'Startup Genome',
        publisherFull: 'Startup Genome',
        sourceUrl: 'https://startupgenome.com/report/gser2024',
        description: 'Ranks startup ecosystems globally based on performance, funding, market reach, talent, and connectedness. Covers 300+ cities and 100+ countries.',
        totalEconomies: 40,
        scoreLabel: 'Rank',
        icon: 'fa-rocket',
        color: '#f59e0b',
        isEcosystems: true,
        data: [
            {rank:1,  code:'us', name:'Silicon Valley',         country:'USA',          note:'$210B+ ecosystem value'},
            {rank:2,  code:'us', name:'New York City',          country:'USA',          note:'FinTech & Media hub'},
            {rank:3,  code:'gb', name:'London',                 country:'UK',           note:'Europe\'s largest hub'},
            {rank:4,  code:'us', name:'Boston',                 country:'USA',          note:'BioTech & DeepTech leader'},
            {rank:5,  code:'cn', name:'Beijing',                country:'China',        note:'AI & Deep Tech center'},
            {rank:6,  code:'cn', name:'Shanghai',               country:'China',        note:'FinTech & Consumer Tech'},
            {rank:7,  code:'us', name:'Los Angeles',            country:'USA',          note:'Media & Consumer Tech'},
            {rank:8,  code:'il', name:'Tel Aviv',               country:'Israel',       note:'Startup Nation capital'},
            {rank:9,  code:'sg', name:'Singapore',              country:'Singapore',    note:'SE Asia gateway'},
            {rank:10, code:'us', name:'Seattle',                country:'USA',          note:'Cloud & E-Commerce'},
            {rank:11, code:'ca', name:'Toronto-Waterloo',       country:'Canada',       note:'AI corridor'},
            {rank:12, code:'fr', name:'Paris',                  country:'France',       note:'Deep Tech & Fashion Tech'},
            {rank:13, code:'in', name:'Bangalore',              country:'India',        note:'India\'s Silicon Valley'},
            {rank:14, code:'nl', name:'Amsterdam',              country:'Netherlands',  note:'Scale-up capital'},
            {rank:15, code:'se', name:'Stockholm',              country:'Sweden',       note:'Spotify, Klarna birthplace'},
            {rank:16, code:'kr', name:'Seoul',                  country:'South Korea',  note:'Mobile & Gaming powerhouse'},
            {rank:17, code:'de', name:'Berlin',                 country:'Germany',      note:'Europe\'s startup hub'},
            {rank:18, code:'au', name:'Sydney',                 country:'Australia',    note:'APAC rising star'},
            {rank:19, code:'us', name:'Chicago',                country:'USA',          note:'FinTech & HealthTech'},
            {rank:20, code:'us', name:'Austin/San Antonio',     country:'USA',          note:'Tech migration magnet'},
            {rank:21, code:'jp', name:'Tokyo',                  country:'Japan',        note:'Robotics & DeepTech'},
            {rank:22, code:'cn', name:'Shenzhen',               country:'China',        note:'Hardware & IoT capital'},
            {rank:23, code:'in', name:'Mumbai',                 country:'India',        note:'FinTech & Media'},
            {rank:24, code:'de', name:'Munich',                 country:'Germany',      note:'Industrial Tech'},
            {rank:25, code:'ch', name:'Zurich',                 country:'Switzerland',  note:'FinTech & Crypto'},
            {rank:26, code:'fi', name:'Helsinki',               country:'Finland',      note:'Gaming & EdTech'},
            {rank:27, code:'dk', name:'Copenhagen',             country:'Denmark',      note:'CleanTech hub'},
            {rank:28, code:'es', name:'Barcelona',              country:'Spain',        note:'Smart Cities leader'},
            {rank:29, code:'ca', name:'Vancouver',              country:'Canada',       note:'Gaming & VR/AR'},
            {rank:30, code:'au', name:'Melbourne',              country:'Australia',    note:'FinTech & RegTech'},
            {rank:31, code:'at', name:'Vienna',                 country:'Austria',      note:'CEE gateway'},
            {rank:32, code:'br', name:'São Paulo',              country:'Brazil',       note:'LATAM\'s largest hub'},
            {rank:33, code:'no', name:'Oslo',                   country:'Norway',       note:'MarTech & OceanTech'},
            {rank:34, code:'ee', name:'Tallinn',                country:'Estonia',      note:'Digital government model'},
            {rank:35, code:'ae', name:'Dubai',                  country:'UAE',          note:'MENA hub, $3B ecosystem'},
            {rank:36, code:'id', name:'Jakarta',                country:'Indonesia',    note:'SE Asia unicorn factory'},
            {rank:37, code:'ie', name:'Dublin',                 country:'Ireland',      note:'Big Tech EMEA base'},
            {rank:38, code:'mx', name:'Mexico City',            country:'Mexico',       note:'LATAM FinTech center'},
            {rank:39, code:'pl', name:'Warsaw',                 country:'Poland',       note:'CEE rising star'},
            {rank:40, code:'kz', name:'Almaty',                 country:'Kazakhstan',   note:'Central Asia\'s top hub'},
        ]
    },

    // ───────────────────────────────────────────────────────
    // 6. GLOBAL CYBERSECURITY INDEX (GCI) 2024 — ITU
    // ───────────────────────────────────────────────────────
    gci: {
        id: 'gci',
        name: 'Global Cybersecurity Index',
        shortName: 'GCI',
        year: 2024,
        publisher: 'ITU',
        publisherFull: 'International Telecommunication Union',
        sourceUrl: 'https://www.itu.int/en/ITU-D/Cybersecurity/Pages/global-cybersecurity-index.aspx',
        description: 'Measures commitment to cybersecurity across 194 countries using five pillars: Legal, Technical, Organizational, Capacity Development, and Cooperation.',
        totalEconomies: 194,
        scoreLabel: 'Tier (1=Highest)',
        isTiered: true,
        icon: 'fa-shield-halved',
        color: '#dc2626',
        data: [
            // Tier 1 (Role Modelling)
            {rank:1,  code:'us', name:'United States',      score:100.0, tier:1, tierName:'Role Modelling'},
            {rank:2,  code:'gb', name:'United Kingdom',     score:99.54, tier:1, tierName:'Role Modelling'},
            {rank:3,  code:'sa', name:'Saudi Arabia',       score:99.54, tier:1, tierName:'Role Modelling'},
            {rank:4,  code:'ee', name:'Estonia',            score:99.48, tier:1, tierName:'Role Modelling'},
            {rank:5,  code:'kr', name:'South Korea',        score:98.52, tier:1, tierName:'Role Modelling'},
            {rank:6,  code:'sg', name:'Singapore',          score:98.52, tier:1, tierName:'Role Modelling'},
            {rank:7,  code:'de', name:'Germany',            score:97.84, tier:1, tierName:'Role Modelling'},
            {rank:8,  code:'fi', name:'Finland',            score:97.50, tier:1, tierName:'Role Modelling'},
            {rank:9,  code:'fr', name:'France',             score:97.36, tier:1, tierName:'Role Modelling'},
            {rank:10, code:'in', name:'India',              score:97.02, tier:1, tierName:'Role Modelling'},
            {rank:11, code:'jp', name:'Japan',              score:96.52, tier:1, tierName:'Role Modelling'},
            {rank:12, code:'ca', name:'Canada',             score:96.13, tier:1, tierName:'Role Modelling'},
            {rank:13, code:'au', name:'Australia',          score:95.60, tier:1, tierName:'Role Modelling'},
            {rank:14, code:'cn', name:'China',              score:95.26, tier:1, tierName:'Role Modelling'},
            {rank:15, code:'ru', name:'Russia',             score:95.26, tier:1, tierName:'Role Modelling'},
            {rank:16, code:'nl', name:'Netherlands',        score:94.78, tier:1, tierName:'Role Modelling'},
            {rank:17, code:'se', name:'Sweden',             score:94.64, tier:1, tierName:'Role Modelling'},
            {rank:18, code:'no', name:'Norway',             score:94.43, tier:1, tierName:'Role Modelling'},
            {rank:19, code:'ae', name:'UAE',                score:94.09, tier:1, tierName:'Role Modelling'},
            {rank:20, code:'il', name:'Israel',             score:93.47, tier:1, tierName:'Role Modelling'},
            // Tier 2 (Advancing)
            {rank:21, code:'at', name:'Austria',            score:92.0,  tier:2, tierName:'Advancing'},
            {rank:22, code:'ch', name:'Switzerland',        score:91.8,  tier:2, tierName:'Advancing'},
            {rank:23, code:'be', name:'Belgium',            score:91.5,  tier:2, tierName:'Advancing'},
            {rank:24, code:'tr', name:'Türkiye',            score:91.2,  tier:2, tierName:'Advancing'},
            {rank:25, code:'br', name:'Brazil',             score:90.9,  tier:2, tierName:'Advancing'},
            {rank:26, code:'dk', name:'Denmark',            score:90.6,  tier:2, tierName:'Advancing'},
            {rank:27, code:'kz', name:'Kazakhstan',         score:90.3,  tier:2, tierName:'Advancing'},
            {rank:28, code:'mx', name:'Mexico',             score:90.0,  tier:2, tierName:'Advancing'},
            {rank:29, code:'pl', name:'Poland',             score:89.7,  tier:2, tierName:'Advancing'},
            {rank:30, code:'uz', name:'Uzbekistan',         score:89.4,  tier:2, tierName:'Advancing'},
            {rank:31, code:'id', name:'Indonesia',          score:89.1,  tier:2, tierName:'Advancing'},
            {rank:32, code:'th', name:'Thailand',           score:88.8,  tier:2, tierName:'Advancing'},
            {rank:33, code:'vn', name:'Vietnam',            score:88.5,  tier:2, tierName:'Advancing'},
            {rank:34, code:'my', name:'Malaysia',           score:88.2,  tier:2, tierName:'Advancing'},
            {rank:35, code:'za', name:'South Africa',       score:87.9,  tier:2, tierName:'Advancing'},
            {rank:36, code:'ro', name:'Romania',            score:87.6,  tier:2, tierName:'Advancing'},
            {rank:37, code:'eg', name:'Egypt',              score:87.3,  tier:2, tierName:'Advancing'},
            {rank:38, code:'ph', name:'Philippines',        score:87.0,  tier:2, tierName:'Advancing'},
            {rank:39, code:'ng', name:'Nigeria',            score:86.7,  tier:2, tierName:'Advancing'},
            {rank:40, code:'ar', name:'Argentina',          score:86.4,  tier:2, tierName:'Advancing'},
            {rank:41, code:'ua', name:'Ukraine',            score:86.1,  tier:2, tierName:'Advancing'},
            {rank:42, code:'ke', name:'Kenya',              score:85.8,  tier:2, tierName:'Advancing'},
            {rank:43, code:'ge', name:'Georgia',            score:85.5,  tier:2, tierName:'Advancing'},
            {rank:44, code:'am', name:'Armenia',            score:85.2,  tier:2, tierName:'Advancing'},
            {rank:45, code:'az', name:'Azerbaijan',         score:84.9,  tier:2, tierName:'Advancing'},
        ]
    }
};

// Uzbekistan profile across all indexes
const UZ_PROFILE = {
    country: 'Uzbekistan',
    code: 'uz',
    indexes: {
        gii:      { rank: 82,  total: 133, score: 29.6, trend: 'up',   change: +3 },
        imd:      { rank: null, total: 67, score: null,  trend: null,   note: 'Not ranked (outside top 67)' },
        egdi:     { rank: 72,  total: 193, score: 0.708, trend: 'up',  change: +8 },
        nri:      { rank: 76,  total: 131, score: 39.6,  trend: 'up',  change: +5 },
        gci:      { rank: 30,  total: 194, score: 89.4,  trend: 'up',  tier: 'Tier 2 – Advancing' },
        startups: { rank: null, total: 40, note: 'No ranked ecosystem yet; Tashkent emerging' }
    },
    highlights: [
        'Ranked Tier 2 (Advancing) in Global Cybersecurity Index 2024 — top 30 globally',
        'Jumped 8 positions in UN E-Government Index 2024 (rank 72)',
        'Improved 5 spots in Network Readiness Index 2023 (rank 76)',
        'Digital Uzbekistan 2030 strategy driving rapid e-government rollout',
        'IT Park Uzbekistan: 700+ resident companies, $300M+ annual exports',
        'One Million Uzbek Coders initiative: 1M+ citizens trained in digital skills',
        'Tashkent emerging as Central Asia\'s fastest-growing startup ecosystem',
    ]
};
